typeof Mugeda=="undefined"&&(Mugeda={});Mugeda.data=Mugeda.data||{};Mugeda.script=Mugeda.script||[];Mugeda.customScript="";Mugeda.scene=void 0;Mugeda.unzipAniData=function(a){a=MugedaCompress.unzip(a);if(a.script&&a.script.length)a.script=unescape(a.script);return a};Mugeda.getFrameLength=function(a){for(var d=1,e=a.length-1;e>=0;e--)for(var b=a[e],g=b.units.length,f=0;f<g;f++){var j=b.units[f],j=j.frameStart+j.frameCount;d<j&&(d=j)}return d};
Mugeda.getWindowSize=function(){var a=document.documentElement,d=a&&a.clientHeight===0;if(typeof document.clientWidth=="number")return{width:document.clientWidth,height:document.clientHeight};else{if(!d){var d=document,e=d.createElement("div");e.style.height="2500px";d.body.insertBefore(e,d.body.firstChild);var b=d.documentElement.clientHeight>2400;d.body.removeChild(e);d=b}if(d)a=document.body;return{width:a.clientWidth,height:a.clientHeight}}};
Mugeda.updateViewport=function(a,d){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;if(_mrmcp.render_mode!="embedded"){var a=a||{width:320,height:480},e=Mugeda.getWindowSize(),b=a.width/a.height,g=e.width/e.height,f=a.width;d&&(f=b>g?a.width:Math.floor(e.width*a.height/e.height));b=document.querySelector("meta[name=viewport]");if(window.previousMugedaViewportWidth==f)return{window:[e.width,e.height],stage:[a.width,a.height]};window.previousMugedaViewportWidth=f;b?b.setAttribute("content","width="+f+(Mugeda.isAndroid&&
Mugeda.androidVersion>3.5?",user-scalable=no":"")):(b=document.createElement("meta"),b.name="viewport",b.content="width="+f+(Mugeda.isAndroid&&Mugeda.androidVersion>3.5?",user-scalable=no":""),document.getElementsByTagName("head")[0].appendChild(b));return{window:[e.width,e.height],stage:[a.width,a.height]}}};Mugeda.getCanvas=function(){return document.getElementsByClassName("MugedaStage")[0]};Mugeda.randPlus=0;
Mugeda.guidGen=function(){var a=new Date-new Date("2012/1/1")+""+Math.random().toString().substr(2,4);return Number(a).toString(36)+""+Mugeda.randPlus++};Mugeda.getMugedaObject=function(){return Mugeda.scene};Mugeda.loadUrl=function(a){return MugedaMraid.loadUrl(a)};Mugeda.enable3DRendering=function(a){a==void 0&&(a=false);this.threeDRendering=a};Mugeda.showFPS=function(){Mugeda.FPSMeter=true};Mugeda.enableNonDisplay=function(a){a==void 0&&(a=false);this.nonDisplay=a};
Mugeda.enableFlexibleFrameRate=function(a){a==void 0&&(a=false);this.flexibleFrameRate=a};Mugeda.enablePulseAnimation=function(a){a==void 0&&(a=false);Mugeda.enablePulse=a};
Mugeda.log=function(a){if(!Mugeda.logConsole)Mugeda.logConsole=document.createElement("div"),Mugeda.logConsole.style.display="block",Mugeda.logConsole.style.position="fixed",Mugeda.logConsole.style.background="#000",Mugeda.logConsole.style.color="#FFF",Mugeda.logConsole.style.left=0,Mugeda.logConsole.style.top=0,document.body.appendChild(Mugeda.logConsole);if(typeof a=="string"||a)Mugeda.logConsole.innerHTML=a;return Mugeda.logConsole.innerHTML};Mugeda.getAudioCache=function(a,d){return Mugeda.currentAni.audioBeList[d]};
window.MugedaCss3=function(a){if(!a){Mugeda.customScript="";var d=function(a){if(/^<.+>$/.test(a))return document.createElement(a.match(/^<(.+)>$/)[1]);else if(/^#.+/.test(a))return document.getElementById(a.match(/^#(.+)/)[1])};d.stage={};d.getAnimation=function(a){return d.stage[a]};d.initAnimation=function(a,d,e,h,c){a=new b(a,d,e,h);Mugeda.currentAni=a;a.initDom(c);return a};d.getCssBackgroundColor=function(a){var e=a.fillInfo;if(e.fillStyle==0)return"rgba("+e.fillColors[0].r+","+e.fillColors[0].g+
","+e.fillColors[0].b+","+e.fillColors[0].a+")";else if(e.fillStyle==1||e.fillStyle==2){var b=e.fillStartPos.x,h=e.fillStartPos.y,c=e.fillEndPos.x,f=e.fillEndPos.y,p=a.rawWidth||a.width,g=a.rawHeight||a.height,a=Math.atan2(f-h,c-b),o=function(a,c,i){return{x:a*Math.cos(i)-c*Math.sin(i),y:a*Math.sin(i)+c*Math.cos(i)}},j=o(0,g,-a).x,r=o(p,g,-a).x,u=o(p,0,-a).x,s=o(b,h,-a).x,n=o(c,f,-a).x,w=Math.max(0,j,r,u),y=Math.min(0,j,r,u),j=function(a,c,i){var d={};d.pm=i;d.r=(c.r-a.r)/(c.pm-a.pm)*(i-a.pm)+parseFloat(a.r);
d.g=(c.g-a.g)/(c.pm-a.pm)*(i-a.pm)+parseFloat(a.g);d.b=(c.b-a.b)/(c.pm-a.pm)*(i-a.pm)+parseFloat(a.b);d.a=(c.a-a.a)/(c.pm-a.pm)*(i-a.pm)+parseFloat(a.a);return d},o=function(a,c){return"rgba("+Math.round(a.r)+","+Math.round(a.g)+","+Math.round(a.b)+","+a.a+") "+(c==void 0?a.pm:c)+"%"};if(e.fillStyle==1){e.fillColors.m_operate(function(a){a.pm=100/(w-y)*(s+(n-s)*a.p-y)+0});for(var b=false,t="",c=0;c<e.fillColors.length;c++)if(h=e.fillColors[c],p=h.pm,b)if(p<100){if(t+=", "+o(h),c==e.fillColors.length-
1){t+=", "+o(h,100);break}}else{t+=", "+o(j(h,e.fillColors[c-1],100),100);break}else{if(p<0)if(c<e.fillColors.length-1)if(e.fillColors[c+1].pm<0)continue;else t+=", "+o(j(h,e.fillColors[c+1],0));else t+=", "+o(h,0),t+=", "+o(h,100);else t+=", "+o(h,0),t+=", "+o(h);b=true}t="linear-gradient("+(d.browser.msie?a*180/Math.PI+90:-a*180/Math.PI)+"deg"+t+")"}else if(e.fillStyle==2){a=Math.sqrt(Math.pow(b-c,2)+Math.pow(h-f,2));t="";for(c=0;c<e.fillColors.length;c++)t+=", "+o(e.fillColors[c],e.fillColors[c].p*
100);t="radial-gradient("+b/p*100+"% "+h/g*100+"%, "+a+"px "+a+"px"+t+")"}return d.css3Per?d.css3Per.toLowerCase()+t:t}else return"transparent"};d.handleCapture=function(a){if(!a.redirected&&d.captureObject!=null){var e=document.createEvent("MouseEvents");e.initMouseEvent(a.type,true,a.cancelable,a.view,a.detail,a.screenX,a.screenY,a.clientX,a.clientY,a.ctrlKey,a.altKey,a.shiftKey,a.metaKey,a.button,a.relatedTarget);e.redirected=true;d.captureObject.object.dispatchEvent(e);a.type=="mouseup"&&d.captureObject&&
d.captureObject.object.m_releasecapture()}};d.getCurrentStyle=function(a,d){if(document.defaultView){var e=document.defaultView.getComputedStyle(a,null);return e?e.getPropertyValue(d):null}else return a.currentStyle[d]};d.getEventPosition=function(a,e){var b,h;if(a.changedTouches){h=a.changedTouches[0];if(h==null)return null;b=h.clientX;h=h.clientY}else b=a.clientX,h=a.clientY;if(e){for(var c=e,f=0,p=0;c&&c.tagName!="BODY";)f+=c.offsetTop,p+=c.offsetLeft,c=c.offsetParent;b=b-p+window.pageXOffset-
parseInt(d.getCurrentStyle(e,"border-left-width"));h=h-f+window.pageYOffset-parseInt(d.getCurrentStyle(e,"border-top-width"))}return{x:b,y:h}};var e=window;(function(){var a=e.performance;d.getTime=a&&(a.now||a.webkitNow)?a[a.now?"now":"webkitNow"].bind(a):function(){return+new Date}})();a=navigator.userAgent.toLowerCase();a={version:(a.match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/)||[0,"0"])[1],safari:/webkit/.test(a),opera:/opera/.test(a),msie:(/msie/.test(a)||/trident/.test(a))&&!/opera/.test(a),mozilla:/mozilla/.test(a)&&
!/(compatible|webkit)/.test(a)&&!/trident/.test(a)};d.browser=a;if(a.safari)d.css3Per="-webkit-",d.css3PerH="webkit";else if(a.opera)d.css3Per="-o-",d.css3PerH="o";else if(a.msie)d.css3Per="",d.css3PerH="";else if(a.mozilla)d.css3Per="-moz-",d.css3PerH="Moz";var b=function(a,d,e,b){this.aniData=a=a.zip?Mugeda.unzipAniData(a):a;this.title=a.title;this.width=a.width;this.height=a.height;this.dom=e;this.rate=a.rate;this.frameTime=1E3/a.rate;this.frameTimeString=this.frameTime+"ms";this.sceneHash={};
this.mainSceneFrameUnitHash={};this.zoneCached={};this.event={};this.stopRedraw=false;this.resDir=b;this.scriptFile="string"==typeof d?d:null;this.frameParamCache={};this.paramUpdatePool={};this.audioList={};this.scriptList=[];if(Mugeda.zoneCache)this.zoneCachedMode=true,this.zoneStart=Mugeda.zoneCache[0],this.zoneEnd=Mugeda.zoneCache[1];Mugeda.updateViewport(this.aniData);setTimeout(function(){window.scroll(0,0)},100)};b.prototype.getScene=function(){return this.scene};var g={mousedown:1,mouseup:1,
click:1,dblclick:1,mouseover:1,mouseout:1,mousemove:1,touchstart:1,touchmove:1,touchend:1,inputstart:2,inputmove:2,inputend:2},f=navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/BlackBerry/i)||navigator.userAgent.match(/Windows Phone/i);window.navigator.userAgent.indexOf("Android");var j=function(a,e,b){a=="inputstart"?a=f?"touchstart":
"mousedown":a=="inputmove"?a=f?"touchmove":"mousemove":a=="inputend"&&(a=f?"touchend":"mouseup");if(g[a]==1&&this.dom){var h=this,c={fun:e,dir:function(a){a.postionGotton=false;a.inputX==void 0&&(Object.defineProperty(a,"inputX",{get:function(){return d.getEventPosition(a,h.thisAni.scene.dom).x}}),Object.defineProperty(a,"inputY",{get:function(){return d.getEventPosition(a,h.thisAni.scene.dom).y}}));e.call(h,a)}};this.event[a]?this.event[a].push(c):this.event[a]=[c];this.dom.addEventListener(a,c.dir,
b||false)}else this.event[a]?this.event[a].push(e):this.event[a]=[e];return this},w=function(a,d,e){a=="inputstart"?a=f?"touchstart":"mousedown":a=="inputmove"?a=f?"touchmove":"mousemove":a=="inputend"&&(a=f?"touchend":"mouseup");if(g[a]==1&&this.dom){if(this.event[a]){for(var b=this.event[a].length-1;b>=0;b--)this.event[a][b].fun&&this.event[a][b].fun==d&&(this.dom.removeEventListener(a,this.event[a][b].dir,e||false),this.event[a].splice(b,1));this.event[a].length==0&&delete this.event[a]}}else if(this.event[a]){for(b=
this.event[a].length-1;b>=0;b--)this.event[a][b]==d&&this.event[a].splice(b,1);this.event[a].length==0&&delete this.event[a]}return this},u=function(a,d,e,b,c){if(this.event[a]){for(var f=[],p=0;p<this.event[a].length;p++)f[p]=this.event[a][p];for(p=0;p<f.length;p++)f[p].call(this,d,e,b,c)}};b.prototype.addEventListener=j;b.prototype.removeEventListener=w;b.prototype.initDom=function(a){function e(){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;var a=Mugeda.getWindowSize();_mrmcp.render_mode!="inline"&&
_mrmcp.render_mode!="embedded"&&a.height>l.height&&B.m_css("margin-top",(a.height-l.height)/2+"px");_mrmcp.render_mode!="inline"&&a.width>l.width&&B.m_css("margin-left",(a.width-l.width)/2+"px")}if(this.aniData&&this.dom){this.thisAni=this;this.countDownRef=0;this.imageCache=[];this.maxNum=0;this.loadOver=a;var l=this.aniData,h=this.dom,c=this;c.iOS=function(){var a={};if(/iP(hone|od|ad)/.test(navigator.platform)){var c=navigator.appVersion.match(/OS (\d+)_(\d+)_?(\d+)?/);a.version=parseInt(c[1],
10)+0.1*parseInt(c[2],10)}return a}();var g=function(a){var c=null;window.weixinAudioLoader&&window.weixinAudioLoader[a]?c=window.weixinAudioLoader[a]:(c=new Audio(a),c.load());c.addEventListener("ended",function(){c.loop?(c.currentTime=0,c.play()):c.currentTime=0});return c},p=function(a,d,e,m,b,i,k,h,l){this.id=a;this.data=d;this.length=Mugeda.getFrameLength(d.layers);this.playing=e;this.currentId=null;this.nextId=0;this.offset=b;this.dom=i;this.layerList=[];this.objectHash={};this.unitHash=[];
this.isSymbol=k;this.clickEventAttached={};this.nameHash={};this.scriptHash={};this.segment={};this.currentSegment={};c.sceneHash[this.id]=this;this.event={};this.frameout=[];this.thisAni=c;this.parentScene=h;this.cachedVisibility={};this.lastRenderList={};this.frameLength=0;if(k)this.object=l;a=k?d.id:"_main";c.frameParamCache[a]=c.frameParamCache[a]||{};this.frameParamCache=c.frameParamCache[a]};p.prototype.getObjectByName=function(a){return this.nameHash[a]};p.prototype.initAndGetDom=function(){var a=
this;a.data.layers.m_operate(function(c){c=new s(c,a);a.layerList.push(c);c.initAndGetDom(a.dom)},true)};p.prototype.play=function(){this.playing=true;c.stopRedraw=false;return this};p.prototype.pause=function(){this.pauseFlag=true;this.playing=false;u.call(this,"pause");return this};p.prototype.gotoAndPlay=function(a){this.gotoFlag=true;this.nextId=a;return this.play()};p.prototype.gotoAndPause=function(a){this.nextId=a;this.gotoFlag=true;return this.pause()};p.prototype.setSegment=function(a,c,
d,e){this.segment[a]={from:Math.min(c,this.length),to:Math.min(d,this.length),isLoop:e};return this};p.prototype.playSegment=function(a){(this.currentSegment=this.segment[a])&&this.gotoAndPlay(this.currentSegment.from);return this};p.prototype.setFrameout=function(a,c){for(var d=this.frameout.length,e=0,b=0;b<this.frameout.length;b++){var i=this.frameout[b];if(e+i.time>a){d=b;break}e+=i.time}this.frameout.splice(d,0,{time:a-e,fun:c});return this};p.prototype.removeChild=function(a){if(a.unit){var c=
a.unit.data.objects;if(a.parentGroup)c=a.parentGroup.data;c.m_operate(function(d,e){if(d.guid==a.id)return c.splice(e,1),false})}a.dom.parentNode.removeChild(a.dom);this.nameHash[a.name]&&delete this.nameHash[a.name];delete this.objectHash[a.id];if(this.scriptHash[a.id])delete this.scriptHash[a.id];else{var d=a.unit?a.unit.data.frameStart:0,e=a.unit?a.unit.data.frameStart+a.unit.data.frameCount:a.currentScene.frameLength-1,b=this.cachedVisibility;setTimeout(function(){for(var c=d;c<=e;c++)for(var k=
b[c].length,i=0;i<k;i++)if(b[c][i].id==a.id){b[c].splice(i,1);break}},0)}return this};p.prototype.appendChild=function(a,c){if(a.name&&this.nameHash[a.name])throw"object name: "+a.name+" had been used";this.nameHash[a.name]=a;for(var d=0;d<(this.frameLength||1);d++)this.cachedVisibility[d]=this.cachedVisibility[d]||[],this.cachedVisibility[d].push(a);a.currentScene=this;a.initAndGetDom(this.dom,c&&c.dom?c.dom:null);Mugeda.nonDisplay?a.hide():a.dom.style.cssText+="display:none";return a};p.prototype.addEventListener=
j;p.prototype.removeEventListener=w;var s=function(a,c){this.id=a.id;this.name=a.name;this.data=a;this.unitList=[];this.scene=c};s.prototype.initAndGetDom=function(a){var c=this;c.data.units.m_operate(function(d){d=new o(d,c);c.unitList.push(d);d.initAndGetDom(a)},true)};var o=function(a,c){this.data=a;this.layer=c;this.objectList=[];this.symbolList=[];this.imageList=[];this.id=a.id;c.scene.unitHash[a.id]=this;c.scene.frameParamCache[this.id]=c.scene.frameParamCache[this.id]||{};this.cachedFrame=
c.scene.frameParamCache[this.id];this.zoneCached=false};o.prototype.initAndGetDom=function(a){var d=this;if(this.data&&(this.data.audio||this.data.audioId))this.audio=this.data.audioId?g(c.resDir+c.audioSym[this.data.audioId]):g(c.resDir+this.data.audio);if(this.audio){for(var e=Mugeda.guidGen(),m=this.layer.scene,b=this.data.frameStart;b<this.data.frameStart+this.data.frameCount;b++)m.cachedAudio=m.cachedAudio||[],m.cachedAudio[b]=m.cachedAudio[b]||[],m.cachedAudio[b].push({audio:this.audio,start:b==
this.data.frameStart,hash:e});c.audioList[e]=this.audio}if(this.data.objects&&this.data.objects.length!=0){if(this.data.keyframes.length)this.data.hashKey={},this.data.keyframes.m_operate(function(a){d.data.hashKey["key_"+a.id]=a});this.data.objects.m_operate(function(c){c=new r(c,d);d.objectList.push(c);c.initAndGetDom(a);if(c.symbolIdList)d.symbolList=d.symbolList.concat(c.symbolIdList);Mugeda.nonDisplay?c.hide():c.dom.style.cssText+="display:none;"});m=this.layer.scene;for(b=this.data.frameStart;b<
this.data.frameStart+this.data.frameCount;b++)m.cachedVisibility[b]=m.cachedVisibility[b]||[],m.cachedVisibility[b]=m.cachedVisibility[b].concat(this.objectList);m.frameLength=Math.max(m.frameLength,this.data.frameStart+this.data.frameCount);if(this.layer.scene.id=="_main")for(b=this.data.frameStart;b<this.data.frameStart+this.data.frameCount;b++)c.mainSceneFrameUnitHash[b]=c.mainSceneFrameUnitHash[b]||[],c.mainSceneFrameUnitHash[b].push(this)}};o.prototype.updateUnitVisibility=function(a){this.objectList.m_operate(function(c){Mugeda.nonDisplay?
a?c.show():c.hide():c.dom.m_css("display",a?c.dom.displayType||"block":"none")})};var x=function(a,c,d,e){this.parent=a;this.dom=c;this.data=a.data.items;this.objectList=[];this.unit=d;this.scene=e};x.prototype.initAndGetDom=function(){var a=this;this.data.length!=0&&this.data.m_operate(function(c){c=new r(c,a.unit,{inGroup:true,group:a});if(!c.currentScene)c.currentScene=a.scene;a.objectList.push(c);c.initAndGetDom(a.dom)})};var r=MugedaCss3.aObject=function(a,d,e){this.data=JSON.parse(JSON.stringify(a));
this.currentScene=(this.unit=d)?d.layer.scene:null;this.id=Mugeda.guidGen();d&&(this.currentScene.nameHash[a.param.name]=this);if(e&&e.inGroup)this.offset={x:0,y:0},this.parentGroup=e.group;this.event={};this.thisAni=c;this.userParam={};var b=[],i=[],h=function(a){if(a.items)for(var c=0;c<a.items.length;c++){var d=a.items[c];d.type==2021||d.type==2023?(b.push(d.guid),i.push(d.param.symbolId)):a.type==2014&&h(d)}};if(a.type==2014)h(a);else if(a.type==2021||a.type==2023)b.push(a.guid),i.push(a.param.symbolId);
if(b.length)this.symbolList=b,this.symbolIdList=i;Object.defineProperty(this,"name",{get:function(){return this.data.param.name},set:function(a){if(this.currentScene.nameHash[a])throw"name had been used before";this.currentScene.nameHash[a]=this.currentScene.nameHash[this.data.param.name];delete this.currentScene.nameHash[this.data.param.name];this.data.param.name=a}});a.type==2005&&Object.defineProperty(this,"src",{get:function(){return this.userParam.src},set:function(a){this.userParam.src=a;this.dom.tagName==
"DIV"?this.dom.childNodes[0].src=a:this.dom.src=a}});Object.defineProperty(this,"width",{get:function(){return this.data.param.width},set:function(a){var c=this.data.param.width/this.scaleX,d=this.rotateCenterX/this.scaleX;this.rotateCenterX=0;this.scaleX=a/c;this.rotateCenterX=d*this.scaleX}});Object.defineProperty(this,"height",{get:function(){return this.data.param.height},set:function(a){var c=this.data.param.height/this.scaleY,d=this.rotateCenterY/this.scaleY;this.rotateCenterY=0;this.scaleY=
a/c;this.rotateCenterY=d*this.scaleY}});Object.defineProperty(this,"left",{get:function(){return this.data.param.left},set:function(a){this.userParam.x=a-this.userParam.ox+this.userParam.rx;this.data.param.left=a;this.data.param.right=this.data.param.left+this.data.param.width;v(this)}});Object.defineProperty(this,"right",{get:function(){return this.data.param.right},set:function(a){this.data.param.right=a;this.data.param.left=a-this.data.param.width;this.userParam.x=this.data.param.left-this.userParam.ox+
this.userParam.rx;v(this)}});Object.defineProperty(this,"top",{get:function(){return this.data.param.top},set:function(a){this.data.param.top=a;this.userParam.y=a-this.userParam.oy+this.userParam.ry;this.data.param.bottom=this.data.param.top+this.data.param.height;v(this)}});Object.defineProperty(this,"bottom",{get:function(){return this.data.param.bottom},set:function(a){this.data.param.bottom=a;this.data.param.top=a-this.data.param.height;this.userParam.y=this.data.param.top-this.userParam.oy+this.userParam.ry;
v(this)}});Object.defineProperty(this,"x",{get:function(){return this.userParam.x},set:function(a){this.userParam.x=a;this.data.param.left=a+this.userParam.ox-this.userParam.rx;this.data.param.right=this.data.param.left+this.data.param.width;v(this)}});Object.defineProperty(this,"y",{get:function(){return this.userParam.y},set:function(a){this.userParam.y=a;this.data.param.top=a+this.userParam.oy-this.userParam.ry;this.data.param.bottom=this.data.param.top+this.data.param.height;v(this)}});Object.defineProperty(this,
"rotateCenterX",{get:function(){return this.userParam.rx},set:function(a){this.data.param.rotateCenterX=this.userParam.rx=Math.round(a);this.userParam.rsx=a/this.userParam.sx;this.userParam.x=this.data.param.left+a-this.userParam.ox;v(this)}});Object.defineProperty(this,"rotateCenterY",{get:function(){return this.userParam.ry},set:function(a){this.data.param.rotateCenterY=this.userParam.ry=Math.round(a);this.userParam.rsy=a/this.userParam.sy;this.userParam.y=this.data.param.top+a-this.userParam.oy;
v(this)}});Object.defineProperty(this,"scaleX",{get:function(){return this.userParam.sx},set:function(a){this.userParam.rx=this.userParam.rx/this.userParam.sx*a;this.userParam.sx=this.data.param.scaleX=a;this.data.param.width=this.data.param.rawWidth*a;this.data.param.left=this.userParam.x+this.userParam.ox-this.userParam.rx;this.data.param.right=this.data.param.left+this.data.param.width;v(this)}});Object.defineProperty(this,"scaleY",{get:function(){return this.userParam.sy},set:function(a){this.userParam.ry=
this.userParam.ry/this.userParam.sy*a;this.userParam.sy=this.data.param.scaleY=a;this.data.param.height=this.data.param.rawHeight*a;this.data.param.top=this.userParam.y+this.userParam.oy-this.userParam.ry;this.data.param.bottom=this.data.param.top+this.data.param.height;v(this)}});Object.defineProperty(this,"rotate",{get:function(){return this.data.param.rotate},set:function(a){this.data.param.rotate=a;v(this)}});Object.defineProperty(this,"alpha",{get:function(){return this.data.param.alpha},set:function(a){this.data.param.alpha=
a;v(this)}});this.userParam.visible=true;Object.defineProperty(this,"visible",{get:function(){return this.userParam.visible},set:function(a){this.userParam.visible=a}});Object.defineProperty(this,"text",{get:function(){if(this.data.type==2010)return unescape(this.data.param.textContent)},set:function(a){if(this.data.type==2010)this.data.param.textContent=escape(a);v(this)}});Object.defineProperty(this,"url",{get:function(){},set:function(a){this.data.param.url=a}})},n={},A=function(){delete n.old;
for(objId in n)n[objId].updateObjectParam();n={}},v=function(a){n[a.id]=a;n.old=true;setTimeout(A,0)};r.prototype.setCapture=function(a){this.dom.m_setCapture(a)};r.prototype.releaseCapture=function(a){this.dom.m_releasecapture(a)};r.prototype.initAndGetDom=function(a,e){var b=this.data,m;if(b.param.left===null)this.unit&&this.unit.data.keyframes&&this.unit.data.keyframes.length>=2?b.param=JSON.parse(JSON.stringify(this.unit.data.keyframes[0].param)):console.log("Fatal error: object (ID: "+b.guid+
") param is lost!");var i=false;if(this.currentScene&&this.currentScene.cachedSymbolScene)var i=true,h=this.currentScene.dom.getElementsByClassName(this.currentScene.cachedSymbolScene.objectHash[b.guid].dom.className)[0];var k=b.param;switch(b.type){case 2003:case 2004:case 2009:if(i)break;var l=k.lineWidth,f=Math.floor(k.lineWidth/2);m=d("<div>");var q=d("<div>");q.m_addClass("guid_"+Mugeda.guidGen());l&&q.m_css("border",l+"px solid "+k.strokeColor).m_css("position","absolute").m_css("top",-f+"px").m_css("bottom",
-f+"px").m_css("left",-f+"px").m_css("right",-f+"px").m_appendTo(m);if(b.type==2009){var g=b.cornerRadius[0]+"px ";m.m_css("border-radius",g+g+g+g);m.m_css("border-top-left-radius",g);m.m_css("border-top-right-radius",g);m.m_css("border-bottom-left-radius",g);m.m_css("border-bottom-right-radius",g)}else if(b.type==2004){var g=k.width/2+"px",o=k.height/2+"px";m.m_css("border-radius",g+" "+o);m.m_css("border-top-left-radius",g+" "+o);m.m_css("border-top-right-radius",g+" "+o);m.m_css("border-bottom-left-radius",
g+" "+o);m.m_css("border-bottom-right-radius",g+" "+o)}m.m_css("background",d.getCssBackgroundColor(k));l&&(b.type==2009?(g=b.cornerRadius[0]+f+"px ",q.m_css("border-radius",g+g+g+g),q.m_css("border-top-left-radius",g),q.m_css("border-top-right-radius",g),q.m_css("border-bottom-left-radius",g),q.m_css("border-bottom-right-radius",g)):b.type==2004&&(g=k.width/2+f+"px",o=k.height/2+f+"px",q.m_css("border-radius",g+" "+o),q.m_css("border-top-left-radius",g+" "+o),q.m_css("border-top-right-radius",g+
" "+o),q.m_css("border-bottom-left-radius",g+" "+o),q.m_css("border-bottom-right-radius",g+" "+o)));break;case 2005:if(!k.imageSrc.length)k.imageSrc="data:image/gif;base64,R0lGODlhAQABAID/AMDAwAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==";if(k.imageSrc.length>0){this.userParam=this.userParam||[];this.userParam.src=c.resDir+k.imageSrc;if(i){l=h;h.tagName=="DIV"&&(l=h.childNodes[0]);c.loadImage("dom_back",{dom:l,url:c.resDir+k.imageSrc,duringBuilding:c.zoneCachedMode,scene:this.currentScene,unit:this.unit});
break}m=d("<img>");if(k.keepAspect){var l=k.rawWidth,f=k.rawHeight,q=k.width,g=k.height,o=q/l*f,j=q,r=j=0;o>g?(o=g,j=(q-g/f*l)/2,m.m_css("padding-left",j.toString()+"px"),m.m_css("padding-right",j.toString()+"px")):(r=(g-o)/2,m.m_css("padding-top",j.toString()+"px"),m.m_css("padding-bottom",j.toString()+"px"))}c.loadImage("dom_back",{dom:m,url:c.resDir+k.imageSrc,duringBuilding:c.zoneCachedMode,scene:this.currentScene,unit:this.unit})}break;case 2010:if(i){h.displayType="table";break}m=d("<div>");
l=d("<div>").m_appendTo(m).m_css("display","table-cell").m_css("vertical-align",k.textVAlign||"baseline");l.displayType="table-cell";l.innerHTML=unescape(k.textContent).replace(/\n/g,"<br>").replace(/\s\s/g," &nbsp;");l.txt=k.textContent;m.m_css("font-size",k.fontSize+"px").m_css("font-weight",k.fontWeight).m_css("font-family",k.fontFamily).m_css("display","table").m_css("text-stroke",k.lineWidth/2+"px "+k.strokeColor).m_css("text-shadow","0 "+(k.lineWidth/2<1?1:k.lineWidth/2)+"px "+k.strokeColor).m_css("line-height",
parseInt(k.fontSize)+4+"px").m_css("text-align",k.textAlign||"left").m_css("text-fill-color",d.getCssBackgroundColor(k)).m_css("color","rgba("+k.fillInfo.fillColors[0].r+","+k.fillInfo.fillColors[0].g+","+k.fillInfo.fillColors[0].b+","+k.fillInfo.fillColors[0].a+")").m_css("padding-top","1px");m.displayType="table";k.fontStyle&&m.m_css("font-style",k.fontStyle);k.textDecoration&&m.m_css("text-decoration",k.textDecoration);break;case 2014:i?m=this.currentScene.dom.getElementsByClassName(this.currentScene.cachedSymbolScene.objectHash[b.guid].dom.className)[0]:
(m=d("<div>"),m.m_addClass("group"));this.group=l=new x(this,m,this.unit,this.currentScene);l.initAndGetDom(m);break;case 2023:l=function(a){return{fillInfo:null,imageSrc:k.imageSrc,rawWidth:k.rawWidth,rawHeight:k.rawHeight*k.frameNum,left:0,right:k.rawWidth,top:-k.rawHeight*a,bottom:k.rawHeight*(k.frameNum-a),scaleX:1,scaleY:1,rotate:0,alpha:1,width:k.rawWidth,height:k.rawHeight*k.frameNum}};f=Mugeda.guidGen();q=Math.ceil(k.frameNum/k.fps*c.rate);c.symbols[f]={id:f,name:f,cw:c.aniData.width,ch:c.aniData.height,
layers:[{id:0,name:"\u56fe\u5c420",units:[{id:Mugeda.guidGen(),layerId:0,frameStart:0,frameCount:q,animated:true,objects:[{guid:Mugeda.guidGen(),type:2005,param:l(0)}],keyframes:[],hashKey:[],visible:true}]}]};g=null;for(o=0;o<q;o++){var n=Math.min(Math.round(o/c.rate*k.fps),k.frameNum-1);n!=g&&(c.symbols[f].layers[0].units[0].keyframes.push({id:o,mode:0,tween:"Step.EaseIn",param:l(n)}),g=n);c.symbols[f].layers[0].units[0].guessKeyframe=false}k.symbolId=f;k.offsetX=-c.aniData.width/2;k.offsetY=-c.aniData.height/
2;case 2021:if(!c.symbols[k.symbolId])break;l=c.symbols[k.symbolId];if(i)f=c.symbols[k.symbolId].cw/2+k.offsetX,q=c.symbols[k.symbolId].ch/2+k.offsetY,f=this.scene=new p(this.data.guid,c.symbols[k.symbolId],true,0,{x:f,y:q},h,true,this.currentScene,this),f.cachedSymbolScene=this.currentScene.cachedSymbolScene.objectHash[b.guid].scene;else{m=d("<div>");m.m_addClass("symbol");b.type==2023&&m.m_css("overflow","hidden");f=c.symbols[k.symbolId].cw/2+k.offsetX;q=c.symbols[k.symbolId].ch/2+k.offsetY;f=this.scene=
new p(this.data.guid,c.symbols[k.symbolId],true,0,{x:f,y:q},m,true,this.currentScene,this);if(b.type==2023){if(k.looped==null)k.looped=true;this.scene.looped=k.looped}if(l.cachedInstance)symCache=l.cachedInstance.scene,f.dom.innerHTML=symCache.dom.innerHTML,f.cachedSymbolScene=symCache}f.initAndGetDom()}if(m||i)if(i)this.dom=h,this.currentScene.objectHash[b.guid]=this,this.updateObjectParam({staticMode:true,readyCachedMode:true,isImage:b.type==2005});else{m.m_addClass("layer_"+(this.unit?this.unit.layer.id:
"script")).m_addClass("guid_"+this.id).m_css("position","absolute").m_css("left",0).m_css("top",0).m_css("backface-visibility","hidden");if(k.vF||k.hF)i=d("<div>").m_css("position","absolute").m_append(m),m.m_css("top","0").m_css("left","0").m_css("right","0").m_css("bottom","0").m_css("transform",(k.vF?"scaleY(-1) ":"")+(k.hF?"scaleX(-1)":"")),m=i,i.className="guid_"+Mugeda.guidGen();a.m_append(m,e);this.dom=m;this.currentScene.objectHash[b.guid]=this;this.updateObjectParam({staticMode:true,isImage:b.type==
2005,dw:j,dh:r})}};r.prototype.addEventListener=j;r.prototype.removeEventListener=w;r.prototype.setParam=function(a){a.call(this,this.param);this.updateObjectParam({param:this.param});Mugeda.nonDisplay?this.param.hide?this.hide():this.show():this.dom.m_css("display",this.param.hide?"none":this.dom.displayType||"block")};r.prototype.getParam=function(){this.param.hide=this.param.hide||false;return this.param};r.prototype.setButton=function(a,c,d){var e=this.scene;e&&(d==void 0&&(d=a),typeof a=="number"&&
(a={from:a,to:a,isLoop:false}),typeof c=="number"&&(c={from:c,to:c,isLoop:false}),typeof d=="number"&&(d={from:d,to:d,isLoop:false}),e.setSegment("__normal",a.from,a.to,a.isLoop),e.setSegment("__push",c.from,c.to,c.isLoop),e.setSegment("__up",d.from,d.to,d.isLoop),e.playSegment("__normal"),this.addEventListener("inputstart",function(){this.disabled||this.scene.playSegment("__push")}),this.addEventListener("inputend",function(){this.scene.currentSegment==e.segment.__push&&this.scene.playSegment("__up")}),
this.addEventListener("mouseout",function(){this.scene.currentSegment==e.segment.__push&&this.scene.playSegment("__up")}));this.dom.m_css("cursor","pointer");return this};r.prototype.appendChild=function(a,c){if(a.name&&this.currentScene.nameHash[a.name])throw"object name: "+a.name+" had been used";this.currentScene.nameHash[a.name]=a;for(var d=this.unit?0:this.unit.data.frameStart,e=this.unit?this.currentScene.frameLength:d+this.unit.data.frameCount;d<e;d++)this.currentScene.cachedVisibility[d]=
this.currentScene.cachedVisibility[d]||[],this.currentScene.cachedVisibility[d].push(a);a.currentScene=this.currentScene;a.initAndGetDom(this.dom,c&&c.dom?c.dom:null);Mugeda.nonDisplay?a.hide():a.dom.style.cssText+="display:none";return a};r.prototype.updateObjectParam=function(a){a=a||{};staticMode=a.staticMode||false;readyCachedMode=a.readyCachedMode||false;var d=this.dom,e=this.offset||this.currentScene.offset,b=a.param||this.data.param,i=this;this.param=b;if(staticMode&&(a.isImage?(b.rawWidth=
b.width-(a.dw?a.dw*2:0),b.rawHeight=b.height-(a.dh?a.dh*2:0)):(b.rawWidth=b.rawWidth||b.width,b.rawHeight=b.rawHeight||b.height),readyCachedMode||(d.m_width(b.rawWidth).m_height(b.rawHeight),(b.vF||b.hF)&&d.childNodes[0].m_width(b.rawWidth).m_height(b.rawHeight)),b.action))if(b.action=="link"&&b.url&&b.url.length){var l=function(){MugedaMraid.openLink(b.url,b.urlTarget)};d.m_css("cursor","pointer").m_event(Mugeda.isAndroid&&Mugeda.androidVersion<3?"click":f?"touchend":"mouseup",function(a){l();a.preventDefault();
a.stopPropagation();return false})}else if(b.action=="form"&&b.form&&b.form.length)l=function(){MugedaBehavior.popupForm(JSON.parse(b.form))},d.m_css("cursor","pointer").m_event(f?"touchend":"mouseup",function(a){l();a.preventDefault();a.stopPropagation();return false});else if(b.action=="behavior"&&b.behavior)a=JSON.parse(b.behavior),b.behaviorObj=a,a.m_operate(function(a){if(a.type=="audio"){var d=a.param.audio_id?c.audioSym[a.param.audio_id]:a.param.audio_url;c.audioBeList=c.audioBeList||{};var b=
Mugeda.guidGen();a.param.audioId=b;c.audioBeList[b]=g(c.resDir+d);a.param.audio_name&&(i.currentScene.nameHash[a.param.audio_name]=c.audioBeList[b]);c.audioList[b]=c.audioBeList[b]}});var a=b.width/b.rawWidth,h=b.height/b.rawHeight,q=b.rotateCenterX!=void 0?b.rotateCenterX:b.width/2,p=b.rotateCenterY!=void 0?b.rotateCenterY:b.height/2,o=Math.round(q/a),j=Math.round(p/h),q=o*a,p=j*h,r=b.left-(o-q)-e.x,n=b.top-(j-p)-e.y,x=b.rotate;r.toString().indexOf("e")>-1&&(r=0);n.toString().indexOf("e")>-1&&(n=
0);a.toString().indexOf("e")>-1&&(a=0);h.toString().indexOf("e")>-1&&(h=0);x.toString().indexOf("e")>-1&&(x=0);this.userParam.x=r+o;this.userParam.y=n+j;this.userParam.rx=q;this.userParam.ry=p;this.userParam.sx=a;this.userParam.sy=h;this.userParam.rsx=o;this.userParam.rsy=j;this.userParam.ox=e.x;this.userParam.oy=e.y;d.m_css("opacity",Math.floor(100*b.alpha)*0.01,c).m_css("transform-origin",o.toString()+"px "+j.toString()+"px",c);this.beforeHiddenTrans="translate("+r.toString()+"px,"+n.toString()+
"px) rotate("+x.toString()+"rad) scale("+a.toString()+","+h.toString()+")";this.hidden||d.m_css("transform",this.beforeHiddenTrans,c);if(b.textContent!=void 0&&d.childNodes[0].txt!=b.textContent)d.childNodes[0].innerHTML=unescape(b.textContent).replace(/\n/g,"<br>"),d.childNodes[0].txt=b.textContent};r.prototype.hide=function(){if(!this.hidden)return this.dom.m_css("transform","translate(-9999999px, -99999999px)",c),this.hidden=true,this};r.prototype.show=function(){if(this.hidden)return this.beforeHiddenTrans&&
this.dom.m_css("transform",this.beforeHiddenTrans,c),this.hidden=false,this};r.prototype.clone=function(a){var c=JSON.parse(JSON.stringify(this.data));c.param.name=a;c.guid=Mugeda.guidGen();return new r(c,null)};a=document.createElement("style");document.getElementsByTagName("head")[0].appendChild(a);c.externalStylesheet=a.sheet||a.styleSheet;c.indexedStylesheet={};c.cachedRule=[];this.dom.m_attr("name",l.title).m_addClass("MugedaStage").m_width(l.width).m_height(l.height).m_css("background-color",
l.color).m_css("background-image",l.image?"url("+l.image+")":"").m_css("background-repeat","no-repeat").m_css("background-size",l.width+"px "+l.height+"px").m_css("overflow","hidden").m_css("position","relative");Mugeda.enablePulse&&this.dom.m_css("transform","translate(0,0)");this.dom.style.webkitTapHighlightColor="rgba(0,0,0,0)";c.loadingDiv=d("<div>").m_css("line-height",l.height+"px").m_css("text-align","center").m_css("background","black").m_css("color","white").m_css("font-family","arial");
c.dom.insertBefore(c.loadingDiv,c.dom.firstChild);c.loadingDiv.innerHTML="Loading...";c.loadingDiv.id="loadingDiv";var B=c.dom;e();c.loadProcess="script";c.updateRuleCached();if(c.aniData.sL)if(Mugeda.previewMode){if(c.aniData.sL.extra&&c.aniData.sL.extra.length)for(a=0;a<c.aniData.sL.extra.length;a++){var y=c.aniData.sL.extra[a];y.indexOf("://")>-1?c.loadImage("script",c.aniData.sL.extra[a]):c.loadImage("script",c.resDir+c.aniData.sL.extra[a])}}else c.aniData.sL.jquery&&c.loadImage("script",c.resDir+
"jquery-1.10.2.min.js"),c.aniData.sL.socketio&&(c.loadImage("script",c.resDir+"socket.io.1.9.16.min.js"),c.loadImage("script",c.resDir+"mugeda_connection.js")),c.aniData.sL.box2d&&c.loadImage("script",c.resDir+"Box2dWeb-2.1.a.3.min.js"),c.aniData.sL.qrcode&&(c.loadImage("script",c.resDir+"qrcode.min.js"),c.loadImage("script",c.resDir+"jquery.qrcode.min.js",1));if(c.aniData.sL&&!Mugeda.previewMode&&(c.aniData.sL.jquery&&c.loadImage("script",c.resDir+"jquery-1.10.2.min.js"),c.aniData.sL.socketio&&(c.loadImage("script",
c.resDir+"socket.io.1.9.16.min.js"),c.loadImage("script",c.resDir+"mugeda_connection.js")),c.aniData.sL.box2d&&c.loadImage("script",c.resDir+"Box2dWeb-2.1.a.3.min.js"),c.aniData.sL.qrcode&&(c.loadImage("script",c.resDir+"qrcode.min.js"),c.loadImage("script",c.resDir+"jquery.qrcode.min.js",1)),c.aniData.sL.extra&&c.aniData.sL.extra.length))for(a=0;a<c.aniData.sL.extra.length;a++)y=c.aniData.sL.extra[a],y.indexOf("://")>-1?c.loadImage("script",c.aniData.sL.extra[a]):c.loadImage("script",c.resDir+c.aniData.sL.extra[a]);
c.scriptFile&&c.loadImage("script",c.resDir+c.scriptFile,2);var t=function(){if(c.scriptFile){if(c.script=Mugeda.script[Mugeda.script.length-1],typeof c.script=="function")c.script(c),c.scriptExeced=true}else if(c.aniData.script)(function(a){eval(a.aniData.script)})(c),Mugeda.customScript=c.aniData.script;var a=function(){delete c.evt;c.loadProcess="image";c.afterLoadScriptProcess()},d={stopLoad:false,goOnLoad:a};c.evt=d;u.call(c,"scriptReady",d);d.stopLoad||a()};c.checkCountDownRef=function(a,d){function b(){for(var a in c.paramUpdatePool){var d=
c.paramUpdatePool[a];d.object.style.cssText+=d.text}c.paramUpdatePool={};a=function(){delete c.evt;c.loadProcess="loaded";c.loadOver.call(c);c.setupTimer()};d={stopLoad:false,goOnLoad:a};c.evt=d;u.call(c,"imageReady",d);d.stopLoad||a()}a||--c.countDownRef;c.countDownRef==0&&(c.loadProcess=="script"?t():c.loadProcess=="image"&&(d?setTimeout(b,10):b()));this.zoneLoadCallback&&this.zoneLoadCallback((this.zoneLoadTotal-this.countDownRef)/this.zoneLoadTotal);return c.countDownRef};c.afterLoadScriptProcess=
function(){if(l.action=="link"&&l.url&&l.url.length){var a=function(){MugedaMraid.openLink(l.url,l.urlTarget)};this.dom.m_css("cursor","pointer").m_event(Mugeda.isAndroid&&Mugeda.androidVersion<3?"click":f?"touchend":"mouseup",function(c){a();c.preventDefault();c.stopPropagation();return false})}l.action=="form"&&l.form&&l.form.length&&(a=function(){MugedaBehavior.popupForm(JSON.parse(l.form))},this.dom.m_css("cursor","pointer").m_event(f?"touchend":"mouseup",function(c){a();c.preventDefault();c.stopPropagation();
return false}));var d=function(a){var b=b||[];(a=a.layers)&&a.m_operate(function(){var a=this.units;a&&a.m_operate(function(){var a=this.objects;if(a){var e=function(){var a=this.type;a==2005?b.push(c.resDir+this.param.imageSrc):a==2021?b=b.concat(d(c.symbols[this.param.symbolId])):a==2014&&this.items.m_operate(function(){e.call(this)})};a.m_operate(function(){e.call(this)})}})});return b};c.symbols={};c.audioSym={};c.symbolsName={};c.aniData.symbols.m_operate(function(a){if(a.type===2)c.audioSym[a.id]=
a.url;else{c.symbols[a.id]=a;c.symbolsName[a.name]=a;var b=99999999,e=-b,i=b,l=-b;a.layers.m_operate(function(a){a.units.m_operate(function(a){a.objects.m_operate(function(a){a=a.param;b=Math.min(b,a.left);e=Math.max(e,a.right);i=Math.min(i,a.top);l=Math.max(l,a.bottom)})})});a.bound={left:b,right:e,top:i,bottom:l,width:e-b,height:l-i};a.zoneCached=false;a.imageList=a.imageList||d(a);var f={guid:Mugeda.guidGen(),type:2021,param:{name:"",fillInfo:{fillStyle:0,fillImage:"",fillColors:[{p:0,r:144,g:200,
b:255,a:1}],fillStartPos:{x:0,y:0},fillEndPos:{x:0,y:0}},rawWidth:a.bound.width,rawHeight:a.bound.height,symbolId:a.id,offsetX:(a.bound.left+a.bound.right-a.cw-a.bound.width)/2,offsetY:(a.bound.top+a.bound.bottom-a.ch-a.bound.height)/2,rotateCenterX:a.bound.width/2,rotateCenterY:a.bound.height/2,strokeType:0,frameRate:12,lineCap:"round",lineJoin:"round",left:-a.bound.width,right:0,top:0,bottom:a.bound.height,scaleX:1,scaleY:1,rotate:0,lineWidth:1,alpha:1,strokeColor:"#0683ff",startX:0,startY:0,endX:a.bound.width,
endY:a.bound.height,width:a.bound.width,height:a.bound.height},curve:{closed:true,points:[]},id:0,items:[],aryAnchors:[]},f=new r(f,null),h={};h.dom=document.createElement("div");h.objectHash={};h.offset={x:a.cw/2+(a.bound.left+a.bound.right-a.cw-a.bound.width)/2,y:a.ch/2+(a.bound.top+a.bound.bottom-a.ch-a.bound.height)/2};f.currentScene=h;f.initAndGetDom(h.dom,null);a.cachedInstance=f}});c.scene=new p("_main",l,true,0,{x:0,y:0},h,false,null,null);c.scene.initAndGetDom();c.updateRuleCached();l.action===
"behavior"&&l.behavior&&c.handleBehavior(l.behavior,c.dom,c.id,c.scene);for(var b in c.scene.unitHash)c.scene.unitHash[b]instanceof o&&c.scene.unitHash[b].updateUnitVisibility(false);c.playTriggered=true;e();window.addEventListener("resize",e);c.checkCountDownRef(true)};c.setupTimer=function(){if(!c.timerSetted){var a;if(Mugeda.FPSMeter){var b=document.createElement("div");b.style.cssText+="position: absolute; left: 0; right: 0; background:black; color:red; z-index:999999; width:2em;";a=function(a){b.innerHTML=
a.toString()};this.dom.appendChild(b);setInterval(function(){Mugeda.FPSMeter&&a(c.fpsFrame);c.fpsFrame=0},1E3)}c.fpsFrame=0;c.timerSetted=true;c.lastFrameTime=d.getTime();c.nextRenderTime=c.lastFrameTime+c.frameTime;c.timeDuring=0;c.dom.removeChild(c.loadingDiv);if(Mugeda.enablePulse&&Mugeda.pulse==null){c.insertRule("@"+d.css3Per+"keyframes MugedaPulse","from {"+d.css3Per+"transform: translate(-100px,0px);}to {"+d.css3Per+"transform: translate(-99px,0px);}");c.insertRule(".MugedaStamp","margin-top:-1em;");
Mugeda.pulse=d("<div>").m_addClass("MugedaStamp");var e=document.getElementsByTagName("body")[0];e.insertBefore(Mugeda.pulse,e.firstChild);Mugeda.pulse.innerHTML="Mugeda";Mugeda.pulse.style[d.css3PerH+"Animation"]="MugedaPulse 1s infinite"}(e=c.dom.m_attr("onRenderReady"))&&eval(e);u.call(c,"renderReady");var i=function(){if(!c.stopRedraw){c.fpsFrame++;var a=d.getTime();if(Mugeda.flexibleFrameRate){var b=a-c.lastFrameTime;if(b>c.frameTime)b=c.frameTime;c.timeDuring=b}for(;z(c.scene,true););if(!(b=
n.old)){var e;a:{for(e in c.paramUpdatePool){e=false;break a}e=true}b=!e}if(b){Mugeda.pulse&&(Mugeda.pulse.style[d.css3PerH+"AnimationPlayState"]="running");n.old&&A();for(var f in c.paramUpdatePool)e=c.paramUpdatePool[f],e.object.style.cssText+=e.text;c.paramUpdatePool={};Mugeda.pulse&&(Mugeda.pulse.style[d.css3PerH+"AnimationPlayState"]="paused")}f=d.getTime();if(Mugeda.flexibleFrameRate)c.lastFrameTime=a,c.timeoutHandle=setTimeout(i,Math.max(40-(f-a),0));else{c.nextRenderTime+=c.frameTime;if(f>
c.nextRenderTime)c.nextRenderTime=f;c.timeoutHandle=setTimeout(i,c.nextRenderTime-f)}}};c.timeoutHandle=setTimeout(i,0)}};c.zoneCachedMode?c.cacheZone(c.zoneStart,c.zoneEnd,null):setTimeout(function(){c.checkCountDownRef(true,true)},0);typeof MugedaBehavior!="undefined"&&MugedaBehavior.processCloseButton&&MugedaBehavior.processCloseButton();var z=function(a){if(a!=null){if(a.currentId==null||a.gotoFlag)a.currentId=a.nextId,a.gotoFlag=false;if(a.pauseFlag&&Mugeda.flexibleFrameRate)a.currentId=Math.floor(a.currentId),
a.nextId=a.currentId,a.pauseFlag=false;for(var d=a.currentId,b=[],e=Math.floor(d),i=a.cachedAudio?a.cachedAudio[e]||[]:[],f=a.playingAudio||[],l={},h=0;h<i.length;h++){var g=i[h];f[g.hash]&&delete f[g.hash];if(g.audio.playStatus!=1)g.audio.play(),g.audio.playStatus=1;l[g.hash]=g}for(hash in f)if(h=f[hash],h.audio)h=h.audio,h.pause(),h.playStatus=0,h.currentTime=0,h.playStatus=0;a.playingAudio=l;f=a.cachedVisibility[e]||[];l={};for(h=0;h<f.length;h++)if(f[h].userParam.visible){if(a.lastRenderList[f[h].id]?
a.lastRenderList[f[h].id]=false:Mugeda.nonDisplay?f[h].show():f[h].dom.m_css("display",f[h].dom.displayType||"block"),l[f[h].id]=f[h],!n[f[h].id]){if(a.lastDrawId!=d&&f[h].unit&&f[h].unit.data.keyframes.length>1&&f[h].unit.data.objects.length==1){if(a.unitHash[f[h].unit.id].cachedFrame[d])i=a.unitHash[f[h].unit.id].cachedFrame[d],f[h].data.param={rawWidth:i.rawWidth,rawHeight:i.rawHeight,width:i.width,height:i.height,rotateCenterX:i.rotateCenterX,rotateCenterY:i.rotateCenterY,left:i.left,top:i.top,
rotate:i.rotate,alpha:i.alpha,behaviorObj:i.behaviorObj,action:i.action};else if((i=TimelineUnit.getKeyframe(f[h].unit.data,d))?Param.exchange(i.param,f[h].data.param,true):(i=TimelineUnit.getTweenParam(f[h].unit.data,d))&&Param.exchange(i,f[h].data.param,true),!Mugeda.flexibleFrameRate)i=f[h].data.param,a.unitHash[f[h].unit.id].cachedFrame[d]={rawWidth:i.rawWidth,rawHeight:i.rawHeight,width:i.width,height:i.height,rotateCenterX:i.rotateCenterX,rotateCenterY:i.rotateCenterY,left:i.left,top:i.top,
rotate:i.rotate,alpha:i.alpha,behaviorObj:i.behaviorObj,action:i.action};b.push(f[h])}if(f[h].symbolList)for(i=0;i<f[h].symbolList.length;i++)if(g=z(c.sceneHash[f[h].symbolList[i]]),typeof g=="string")return g;else b=b.concat(g);a.lastDrawId!=d&&(i=f[h].data.param.behaviorObj||f[h].data.param.behavior,f[h].data.param.action=="behavior"&&i&&c.handleBehavior(i,f[h].dom,f[h].id,a,f[h].unit))}}else Mugeda.nonDisplay?f[h].hide():f[h].dom.m_css("display","none");for(var q in a.lastRenderList)a.lastRenderList[q]&&
(Mugeda.nonDisplay?a.lastRenderList[q].hide():a.lastRenderList[q].dom.m_css("display","none"));a.lastRenderList=l;if(a.playing&&!a.gotoFlag)Mugeda.flexibleFrameRate?a.nextId=a.currentId+c.timeDuring/c.frameTime:a.nextId++;for(u.call(a,"enterframe");a.frameout.length&&a.frameout[0].time==0;)q=a.frameout[0].fun,a.frameout.splice(0,1),q.call(a);a.frameout.length&&a.frameout[0].time--;if(a.currentSegment&&a.currentSegment.from!=void 0)q=a.currentSegment,a.nextId>q.to&&(q.isLoop?a.gotoAndPlay(a.currentSegment.from):
(a.gotoAndPause(q.to),a.lastDrawId!=d&&u.call(a,"segmentend")));else if(a.nextId>=a.length)a.id=="_main"&&!c.aniData.loop?a.nextId=a.length-1:a.looped==false?a.nextId=a.length-1:(a.nextId=0,showAnimation=false);a.currentId=a.nextId;a.lastDrawId=d;if(a.pauseFlag&&Mugeda.flexibleFrameRate&&d!=e)return"inval";if(a.id!="_main")return b;else{for(h=0;h<b.length;h++)b[h].updateObjectParam();return null}}};b.prototype.createInstanceOfSymbol=function(a,d){var b=c.symbolsName[a];if(b)return b={guid:Mugeda.guidGen(),
type:2021,param:{name:d,fillInfo:{fillStyle:0,fillImage:"",fillColors:[{p:0,r:144,g:200,b:255,a:1}],fillStartPos:{x:0,y:0},fillEndPos:{x:0,y:0}},rawWidth:b.bound.width,rawHeight:b.bound.height,symbolId:b.id,offsetX:(b.bound.left+b.bound.right-b.cw-b.bound.width)/2,offsetY:(b.bound.top+b.bound.bottom-b.ch-b.bound.height)/2,rotateCenterX:b.bound.width/2,rotateCenterY:b.bound.height/2,strokeType:0,frameRate:12,lineCap:"round",lineJoin:"round",left:-b.bound.width,right:0,top:0,bottom:b.bound.height,scaleX:1,
scaleY:1,rotate:0,lineWidth:1,alpha:1,strokeColor:"#0683ff",startX:0,startY:0,endX:b.bound.width,endY:b.bound.height,width:b.bound.width,height:b.bound.height},curve:{closed:true,points:[]},id:0,items:[],aryAnchors:[]},new r(b,null)};b.prototype.unloadAnimation=function(){this.stopRedraw=true;this.dom&&this.dom.parentNode.removeChild(this.dom)}}};b.prototype.checkLoad=function(a){a&&--this.imageNum;this.zoneLoadCallback&&this.zoneLoadCallback((this.zoneLoadTotal-this.imageNum)/this.zoneLoadTotal);
this.imageNum==0&&(this.loadOver.call(this),this.setupTimer())};b.prototype.loadAudio=function(a){b.prototype.loadImage("audio",a)};b.prototype.loadImage=function(a,b,d){d==null&&(d=0);var e=this;e.countDownRef=e.countDownRef||0;if(a=="dom_back"){var d=b.dom,c=b.url,a=b.duringBuilding||false,f=b.cacheZone||false;if(e.imageCache[c])if(e.imageCache[c].loaded){if(d)d.src=c;return false}else if(f){if(e.imageCache[c].loading)return false;var g=new Image;g.src=c;g.url=c;e.imageCache[c].loaded=true;e.countDownRef++;
e.maxNum=e.countDownRef;g.m_event("load",function(){e.checkCountDownRef();e.imageCache[this.url].dom.m_operate(function(){this.src=c})}).m_event("error",function(){console.log("Error when loading image: "+g.src);e.checkCountDownRef()});return e.imageCache[c].loading=true}else return e.imageCache[c].dom.push(d),a&&b.scene&&b.scene.id=="_main"&&(b.unit.imageList[c]=e.imageCache[c]),false;else return a?(e.imageCache[c]={image:null,url:c,dom:[d],loaded:false,duringBuilding:true},b.scene&&b.scene.id==
"_main"&&(b.unit.imageList[c]=e.imageCache[c]),false):(g=new Image,g.src=c,g.url=c,e.imageCache[c]={image:g,dom:[d],loaded:false},e.countDownRef++,e.maxNum=e.countDownRef,g.m_event("load",function(){e.imageCache[this.url].loaded=true;e.loadingDiv.innerHTML="Loading..."+(e.maxNum-e.countDownRef+1)+"/"+e.maxNum;e.checkCountDownRef();e.imageCache[this.url].dom.m_operate(function(){this.src=c})}).m_event("error",function(){e.loadingDiv.innerHTML="Loading..."+(e.maxNum-e.countDownRef+1)+"/"+e.maxNum;e.checkCountDownRef();
console.log("Error when loading image: "+g.src)}),true)}else if(a=="script"){e.countDownRef++;e.maxNum=e.countDownRef;for(a=e.scriptList.length;a<d;a++)e.scriptList[a]=[];e.scriptList[d]=e.scriptList[d]||[];e.scriptList[d].push(b);if(typeof j!="undefined")return Mugeda.loadJs(b);var j=-1;if(!e.scriptLoadTimer)e.scriptLoadTimer=setTimeout(function(){var a=function(c){if(!(c>=e.scriptList.length)){var b=e.scriptList[c];b||a(++c);for(var d=b.length,i=0;i<b.length;i++)Mugeda.loadJs(b[i],function(){e.loadingDiv.innerHTML=
"Loading..."+(e.maxNum-e.countDownRef+1)+"/"+e.maxNum;e.checkCountDownRef();--d==0&&a(++c)},function(){console.log("Error when loading user script");e.loadingDiv.innerHTML="Loading..."+(e.maxNum-e.countDownRef+1)+"/"+e.maxNum;e.checkCountDownRef();--d==0&&a(++c)});b.length==0&&a(++c)}};a(++j)},0)}else a="audio"};b.prototype.cacheZone=function(a,b,d,e){var c=this;if(b==null||b<a)b=a;a<1&&(a=1);if(b>c.scene.length)b=c.scene.length;d==null&&(d=[]);c.zoneCachedMode=true;c.zoneLoadCallback=e||function(){};
var f={},g={},j=0;for(a-=1;a<b;a++)c.zoneCached[a]||(c.mainSceneFrameUnitHash[a].m_operate(function(){if(!this.zoneCached){this.symbolList.m_operate(function(){c.symbols[this.toString()]&&(f[this.toString()]=c.symbols[this.toString()])});d.m_operate(function(){var a=this.toString();f[c.symbolsName[a].id]=c.symbolsName[a]});var a=this.imageList;for(e in a)a[e].loaded==false&&(g[e]=a[e]);for(var b in f)if(a=f[b],a.zoneCached==false)a.imageList.m_operate(function(){var a=this.toString();g[a]||(g[a]=
{dom:[],url:a})}),a.zoneCached=true;for(var e in g)g[e].url&&c.loadImage("dom_back",{url:e,cacheZone:true,dom:[]})&&j++;this.zoneCached=true}}),c.zoneCached[a]=true);c.zoneLoadTotal=j;j==0&&(b=(this.zoneLoadTotal-this.countDownRef)/this.zoneLoadTotal,c.zoneLoadCallback(b?b:1))};var s=function(a){var b=a.className,d=b.indexOf("guid");return d>-1?(a=b.indexOf(" ",d),a==-1?b.substr(d):b.substr(d,a-d)):(b="guid_"+Mugeda.guidGen(),a.m_addClass(b),b)};b.prototype.insertRuleCached=function(a,b){if(this.cachedRule){if(this.cachedRule.push({obj:a,
cssText:b}),!this.waitToupdateRuleCached){this.waitToupdateRuleCached=true;var d=this;setTimeout(function(){d.updateRuleCached()},0)}}else this.insertRule("."+s(a),b)};b.prototype.updateRuleCached=function(){for(var a=0;a<this.cachedRule.length;a++){var b=this.cachedRule[a];this.insertRule("."+s(b.obj),b.cssText)}this.cachedRule=[];delete this.waitToupdateRuleCached};b.prototype.insertRule=function(a,b){var d=this.externalStylesheet,e=this.indexedStylesheet;if(e[a])e[a].style.cssText+=b;else{var c=
0,f=d.rules?d.rules.length:d.cssRules.length;d.insertRule?c=d.insertRule(a+"{"+b+"}",f):d.addRule&&(c=d.addRule(a,b,f));e[a]=d.rules?d.rules[c]:d.cssRules[c]}};b.prototype.handleBehavior=function(a,b,d,e,c){var g=this;(typeof a=="string"?JSON.parse(a):a).m_operate(function(a,i){var j=null;a.unit=c?c.data||{}:{};a.param=a.param||{};var n=a.param.scope=="symbol"?e:g.scene;if(a.type=="play")j=function(){n.play.call(n)};else if(a.type=="pause")j=function(){n.pause.call(n)};else if(a.type=="gotoAndPlay")parseInt(a.param.frame_number),
j=function(){n.gotoAndPlay.call(n,parseInt(a.param.frame_number)-2+1)};else if(a.type=="gotoAndStop"||a.type=="gotoAndPause")parseInt(a.param.frame_number),j=function(){n.gotoAndPause.call(n,parseInt(a.param.frame_number)-1+1)};else if(a.type=="next")parseInt(a.param.frame_number),j=function(){n.gotoAndPause.call(n,Math.min(n.length,n.currentId+1+1))};else if(a.type=="previous")parseInt(a.param.frame_number),j=function(){n.gotoAndPause.call(n,Math.max(1,n.currentId-1+1))};else if(a.type!="callback")if(a.type==
"audio"){if(a.param.audio_id)a.param.audio_url=g.audioSym[a.param.audio_id]}else a.type=="stopAllAudio"&&(j=function(){for(var a in g.audioList){var c=g.audioList[a];try{c.pause(),c.currentTime=0}catch(b){}}});if(a.event=="click"){if(!n.clickEventAttached[d+"_"+i])b.style.cursor="pointer",b.m_event(f?"touchend":"mouseup",function(c){MugedaBehavior.processAction(a,"click",true);j&&j.call();c.preventDefault();c.stopPropagation();return false}),n.clickEventAttached[d+"_"+i]=true}else a.event=="appear"&&
(j?j():MugedaBehavior.processAction(a,"appear",true))})};window.HTMLElement.prototype.m_attr=function(a,b){return typeof b!="undefined"?(this.setAttribute(a,b),this):this.getAttribute(a)};window.HTMLElement.prototype.m_addClass=function(a){if(a&&typeof a==="string")this.className=this.className?this.className+" "+a:a;return this};window.HTMLElement.prototype.m_removeClass=function(a){if(a&&typeof a==="string"&&this.className)this.className=this.className.replace(RegExp("("+a+"\\s)|(\\s*"+a+")"),"");
return this};window.HTMLElement.prototype.m_event=function(a,b,e){/(transition)|(other)/.test(a)&&(a=d.css3Per+(d.css3Per?a.substr(0,1).toUpperCase():a.substr(0,1))+a.substr(1));this.addEventListener(a,b,e||false);return this};var n={transform:d.css3Per+"transform",transition:d.css3Per+"transition",textStroke:d.css3Per+"textStroke",textFillColor:d.css3Per+"textFillColor","transform-origin":d.css3Per+"transform-origin"};window.HTMLElement.prototype.m_css=function(a,b,e){n[a]&&(a=n[a]);if(b!=void 0)if(e){if(this.guid==
null)this.guid=Mugeda.guidGen();e.paramUpdatePool[this.guid]==null&&(e.paramUpdatePool[this.guid]={object:this,text:""});e.paramUpdatePool[this.guid].text+=a+":"+b+";"}else a.indexOf("opacity")>-1||a.indexOf("tran")>-1||!Mugeda.nonDisplay&&a.indexOf("display")>-1||!Mugeda.nonDisplay&&a.indexOf("vertical")>-1?this.style.cssText+=a+":"+b+";":Mugeda.currentAni.insertRuleCached(this,a+":"+b+";");else return d.getCurrentStyle(this,a);return this};window.HTMLElement.prototype.m_width=function(a){if(a!=
void 0)return this.m_css("width",a+"px")};window.HTMLElement.prototype.m_height=function(a){if(a!=void 0)return this.m_css("height",a+"px")};window.HTMLElement.prototype.m_transform=function(a,b,d,e,c,f,g){data={};a!=null&&(data.translateX=a.toString()+"px");b!=null&&(data.translateY=b.toString()+"px");d!=null&&(data.rotate=d.toString()+"rad");e!=null&&(data.scaleX=e.toString());e!=null&&(data.scaleY=c.toString());Mugeda.threeDRendering&&(data.translateZ="0px");var a="",j;for(j in data)a+=j+"("+data[j]+
") ";if(f!=null||g!=null)this.m_css("transform-origin",(Math.abs(f)<0.01?0:Math.floor(100*f)*0.01)+"px "+(Math.abs(g)<0.01?0:Math.floor(100*g)*0.01)+"px");return this.m_css("transform",a)};window.HTMLElement.prototype.m_append=function(a,b){a instanceof window.HTMLElement&&(b?this.insertBefore(a,b):this.appendChild(a));return this};window.HTMLElement.prototype.m_appendTo=function(a){a instanceof window.HTMLElement&&a.appendChild(this);return this};window.HTMLElement.prototype.m_setCapture=function(a){MugedaCss3.captureObject=
{object:this,capture:a==void 0?true:a};return this};window.HTMLElement.prototype.m_releasecapture=function(){MugedaCss3.captureObject=null;return this};Array.prototype.m_operate=function(a,b){for(var d=b?this.length-1:0;b&&d>=0||!b&&d<this.length;b?d--:d++)if(a.call(this[d],this[d],d)==false)break};String.prototype.m_trim=function(){return this.replace(/(^\s*)|(\s*$)/g,"")};return d}}(window.MugedaCss3);
var MugedaCompress={keys:"Ac,action,fM,form,tt,title,wt,width,ht,height,cl,color,sm,symbols,ly,layers,vr,version,sC,scripts,zI,zoomInfo,pd,pid,tp,type,nm,name,un,units,lI,layerId,fS,frameStart,fC,frameCount,ad,animated,vb,visible,ob,objects,pm,param,fI,fillInfo,cv,curve,kf,keyframes,md,mode,tw,tween,hK,hashKey,ix,index,rW,rawWidth,rH,rawHeight,sI,symbolId,oX,offsetX,oY,offsetY,rX,rotateCenterX,rY,rotateCenterY,it,items,nI,nodeId,gP,guidPath,ph,path,gi,guid,sm,smooth,iX,innerX,iY,innerY,uX,outerX,uY,outerY,cX,centerX,cY,centerY,ed,edges,st,section,fZ,fontSize,fT,fontStyle,fW,fontWeight,fF,fontFamily,tA,textAlign,tC,textContent,tD,textDecoration,cR,cornerRadius,iS,imageSrc,lC,lineCap,lJ,LineJoin,fR,frameRate,iP,innerPercent,TA,trackAnchors,MT,mugedaTrackAnchors".split(","),unzip:function(a){if(!a)return a;
if(a.zip!=1)return HaniData.unzip(a);a=JSON.parse(JSON.stringify(a));a=MugedaCompress.unzipKey(a);delete a.zip;if(a.rate==void 0)a.rate=12;if(a.width==void 0)a.width=600;if(a.height==void 0)a.height=400;if(a.guid==void 0)a.guid="";if(a.title==void 0)a.title="";if(a.script==void 0)a.script="";if(a.loop==void 0)a.loop=true;if(a.useCamera==void 0)a.useCamera=false;if(a.symbols==void 0)a.symbols=[];if(a.symbols.length)for(var d=a.symbols,e=0;e<d.length;e++){var b=d[e];b.runtime=true;b.dirtyFlag=false;
MugedaCompress.unzipLayers(b.layers)}MugedaCompress.unzipZoomInfo(a);MugedaCompress.unzipLayers(a.layers);return a},unzipKey:function(a){for(var d,a=JSON.stringify(a),e=0;e<MugedaCompress.keys.length;e+=2)d=eval('/"'+MugedaCompress.keys[e]+'":/g'),a=a.replace(d,'"'+MugedaCompress.keys[e+1]+'":');return JSON.parse(a)},unzipZoomInfo:function(a){for(var d=[],e=a.zoomInfo.split(",")||[],b=0;b<e.length;b+=4){var g=e[b];if(g.indexOf("i")==0){g=g.substr(1);b++;var f=e[b];f.indexOf("t")==0?(f=f.substr(1),
b++):f=null;d[g]={offsetLeft:Number(e[b]),offsetTop:Number(e[b+1]),rotation:Number(e[b+2]),zoomLevel:Number(e[b+3])};if(f)d[g].tween=f}}a.zoomInfo=d},unzipLayers:function(a){for(var d=0;d<a.length;d++){var e=a[d];e.hide=false;e.lock=false;for(var e=e.units,b=0;b<e.length;b++){var g=e[b];g.animated&&MugedaCompress.unzipPath(g);for(var f=g.keyframes||[],j=0;j<f.length;j++)MugedaCompress.unzipParam(f[j].param);if(g.visible==void 0)g.visible=true;MugedaCompress.unzipObjects(g.objects)}}},unzipPath:function(a){for(var d=
a.path.split(","),e=[],b=d.shift(),g=d.shift(),f=0;f<d.length;f+=7)e.push({id:Number(d[f]),backwardX:Number(d[f+1]),backwardY:Number(d[f+2]),forwardX:Number(d[f+3]),forwardY:Number(d[f+4]),nodeX:Number(d[f+5]),nodeY:Number(d[f+6])});e.length?(a.pathLeft=Number(b),a.pathTop=Number(g),a.path=e):(delete a.path,delete a.pathLeft,delete a.pathTop)},unzipObjects:function(a){for(var d=0;d<a.length;d++){var e=a[d];e.items&&e.items.length?MugedaCompress.unzipObjects(e.items):(e.id=0,e.name="",e.items=[],e.aryAnchors=
[]);MugedaCompress.unzipCurve(e);MugedaCompress.unzipParam(e.param)}},unzipCurve:function(a){var d=a.curve;if(typeof d=="string"){a.curve={};var d=d.split(","),e=d.shift()==1;a.curve.closed=e;for(var e=[],b=0;b<d.length;b+=6)e.push({backwardX:Number(d[b]),backwardY:Number(d[b+1]),forwardX:Number(d[b+2]),forwardY:Number(d[b+3]),nodeX:Number(d[b+4]),nodeY:Number(d[b+5])});a.curve.points=e}},unzipParam:function(a){if(a.strokeType==void 0)a.strokeType=0;if(a.frameRate==void 0)a.frameRate=12;if(a.lineCap==
void 0)a.lineCap="round";if(a.lineJoin==void 0)a.lineJoin="round";for(var d=a.m.split(";"),e=0;e<d.length;e++){var b=d[e].substr(0,1),g=d[e].substr(1);switch(b){case "L":a.left=Number(g);break;case "R":a.right=Number(g);break;case "T":a.top=Number(g);break;case "B":a.bottom=Number(g);break;case "S":a.startX=Number(g);break;case "P":a.startY=Number(g);break;case "E":a.endX=Number(g);break;case "N":a.endY=Number(g);break;case "X":a.scaleX=Number(g);break;case "Y":a.scaleY=Number(g);break;case "O":a.rotate=
Number(g);break;case "W":a.lineWidth=Number(g);break;case "A":a.alpha=Number(g);break;case "C":a.strokeColor=g}}if(a.startX==void 0)a.startX=a.left;if(a.startY==void 0)a.startY=a.top;if(a.endX==void 0)a.endX=a.right;if(a.endY==void 0)a.endY=a.bottom;a.width=a.right-a.left;a.height=a.bottom-a.top;delete a.m;MugedaCompress.unzipFillInfo(a)},unzipFillInfo:function(a){if(a.fillInfo){for(var d=a.fillInfo.split(";"),e=Number(d[0]),b=d[1].split(","),g=d[3],f=[],j=0;j<b.length;j+=5)f.push({p:Number(b[j]),
r:Number(b[j+1]),g:Number(b[j+2]),b:Number(b[j+3]),a:Number(b[j+4])});e={fillStyle:e,fillImage:g,fillColors:f};d=d[2].split(",");d.length!=4&&(d=[0,0,0,0]);e.fillStartPos={x:Number(d[0]),y:Number(d[1])};e.fillEndPos={x:Number(d[2]),y:Number(d[3])};a.fillInfo=e}}},TimelineUnit={getKeyframe:function(a,d){var e=a.hashKey["key_"+d];e||(e=null);return e},getTweenParam:function(a,d){var e=a.keyframes.length,b=a.keyframes[0],g=null,f=null,j=0,w=-1;bezierInterpolate=function(a,b,d,c,e,f){return Math.pow(b,
3)*d+3*Math.pow(b,2)*a*c+3*b*Math.pow(a,2)*e+Math.pow(a,3)*f};var u=function(a,b,d){var c=1-d,e=a.nodeY,f=a.forwardY,g=b.backwardY,i=b.nodeY,a=bezierInterpolate(d,c,a.nodeX,a.forwardX,b.backwardX,b.nodeX),d=bezierInterpolate(d,c,e,f,g,i);return{x:a,y:d}};if(e>1&&!a.hashKey["key_"+d]){for(var s=1;s<e;s++){g=a.keyframes[s];if(g.id>d){w=s;break}b=g;j=s;g=null}if(g){e=Math.abs(g.id-b.id);f=d-b.id;e=TimelineUnit.getTweenFactors(e,b.tween);if(Mugeda.flexibleFrameRate){e.push(1);var s=Math.floor(f),n=Math.ceil(f),
i=e[s],e=e[n],e=n==s?e:(f-n)*(e-i)/(n-s)+e}else e=e[f];f={left:0,top:0,right:0,bottom:0,startX:0,startY:0,endX:0,endY:0,width:0,height:0,alpha:1,rotate:0,scaleX:1,scaleY:1,lineWidth:1,strokeType:0,strokeColor:"#0683ff",lineCap:"round",lineJoin:"round",fillInfo:{fillStyle:0,fillImage:"",fillStartPos:{x:32,y:10},fillEndPos:{x:80,y:100},fillColors:[{p:0,r:144,g:200,b:255,a:1},{p:0.8,r:255,g:144,b:200,a:1},{p:1,r:200,g:255,b:144,a:1}]}};Param.tweenParam(f,b.param,g.param,e);if(a.pathMode>Hanimation.PATHMODE_DEFAULT&&
j>=0&&w>=0)g=a.path,j=u(g[j],g[w],e),j.x=a.pathLeft+j.x-f.rotateCenterX,j.y=a.pathTop+j.y-f.rotateCenterY,f.startX=j.x,f.startY=j.y,f.endX=f.startX+f.width,f.endY=f.startY+f.height,f.left=f.startX,f.top=f.startY,f.right=f.endX,f.bottom=f.endY}}if(!f)f=b.param;return f},getTweenFactors:function(a,d){var e=[],b=new TWEEN.Tween({x:0});b.to({x:1},1E3);d||(d="Linear.EaseNone");for(var d=d.split("."),g=d.length,f=TWEEN.Easing;g;)f=f[d[d.length-g]],g--;b.easing(f);for(g=0;g<a;g++)e[g]=b.getFactor(g/a);return e}},
TWEEN=TWEEN||function(){var a,d,e,b,g=[];return{start:function(a){e=setInterval(this.update,1E3/(a||60))},stop:function(){clearInterval(e)},add:function(a){g.push(a)},getAll:function(){return g},removeAll:function(){g=[]},remove:function(b){a=g.indexOf(b);a!==-1&&g.splice(a,1)},update:function(){a=0;d=g.length;for(b=(new Date).getTime();a<d;)g[a].update(b)?a++:(g.splice(a,1),d--)}}}();
TWEEN.Tween=function(a){var d={},e={},b={},g=1E3,f=0,j=null,w=TWEEN.Easing.Linear.EaseNone,u=null,s=null,n=null;this.to=function(d,e){e!==null&&(g=e);for(var f in d)a[f]!==null&&(b[f]=d[f]);return this};this.start=function(){TWEEN.add(this);j=(new Date).getTime()+f;for(var g in b)a[g]!==null&&(d[g]=a[g],e[g]=b[g]-a[g]);return this};this.stop=function(){TWEEN.remove(this);return this};this.delay=function(a){f=a;return this};this.easing=function(a){w=a;return this};this.chain=function(a){u=a};this.onUpdate=
function(a){s=a;return this};this.onComplete=function(a){n=a;return this};this.getFactor=function(a){a=Math.min(1,Math.max(0,a));return w(a)};this.update=function(b){var f,l;if(b<j)return true;b=(b-j)/g;b=b>1?1:b;l=w(b);for(f in e)a[f]=d[f]+e[f]*l;s!==null&&s.call(a,l);return b==1?(n!==null&&n.call(a),u!==null&&u.start(),false):true}};TWEEN.Easing={Linear:{},Quadratic:{},Cubic:{},Quartic:{},Quintic:{},Sinusoidal:{},Exponential:{},Circular:{},Elastic:{},Back:{},Bounce:{},Step:{}};
TWEEN.Easing.Linear.EaseNone=function(a){return a};TWEEN.Easing.Quadratic.EaseIn=function(a){return a*a};TWEEN.Easing.Quadratic.EaseOut=function(a){return-a*(a-2)};TWEEN.Easing.Quadratic.EaseInOut=function(a){return(a*=2)<1?0.5*a*a:-0.5*(--a*(a-2)-1)};TWEEN.Easing.Cubic.EaseIn=function(a){return a*a*a};TWEEN.Easing.Cubic.EaseOut=function(a){return--a*a*a+1};TWEEN.Easing.Cubic.EaseInOut=function(a){return(a*=2)<1?0.5*a*a*a:0.5*((a-=2)*a*a+2)};TWEEN.Easing.Quartic.EaseIn=function(a){return a*a*a*a};
TWEEN.Easing.Quartic.EaseOut=function(a){return-(--a*a*a*a-1)};TWEEN.Easing.Quartic.EaseInOut=function(a){return(a*=2)<1?0.5*a*a*a*a:-0.5*((a-=2)*a*a*a-2)};TWEEN.Easing.Quintic.EaseIn=function(a){return a*a*a*a*a};TWEEN.Easing.Quintic.EaseOut=function(a){return(a-=1)*a*a*a*a+1};TWEEN.Easing.Quintic.EaseInOut=function(a){return(a*=2)<1?0.5*a*a*a*a*a:0.5*((a-=2)*a*a*a*a+2)};TWEEN.Easing.Sinusoidal.EaseIn=function(a){return-Math.cos(a*Math.PI/2)+1};
TWEEN.Easing.Sinusoidal.EaseOut=function(a){return Math.sin(a*Math.PI/2)};TWEEN.Easing.Sinusoidal.EaseInOut=function(a){return-0.5*(Math.cos(Math.PI*a)-1)};TWEEN.Easing.Exponential.EaseIn=function(a){return a==0?0:Math.pow(2,10*(a-1))};TWEEN.Easing.Exponential.EaseOut=function(a){return a==1?1:-Math.pow(2,-10*a)+1};TWEEN.Easing.Exponential.EaseInOut=function(a){return a==0?0:a==1?1:(a*=2)<1?0.5*Math.pow(2,10*(a-1)):0.5*(-Math.pow(2,-10*(a-1))+2)};
TWEEN.Easing.Circular.EaseIn=function(a){return-(Math.sqrt(1-a*a)-1)};TWEEN.Easing.Circular.EaseOut=function(a){return Math.sqrt(1- --a*a)};TWEEN.Easing.Circular.EaseInOut=function(a){return(a/=0.5)<1?-0.5*(Math.sqrt(1-a*a)-1):0.5*(Math.sqrt(1-(a-=2)*a)+1)};TWEEN.Easing.Elastic.EaseIn=function(a){var d,e=0.1,b=0.25;if(a==0)return 0;if(a==1)return 1;b||(b=0.3);!e||e<1?(e=1,d=b/4):d=b/(2*Math.PI)*Math.asin(1/e);return-(e*Math.pow(2,10*(a-=1))*Math.sin((a-d)*2*Math.PI/b))};
TWEEN.Easing.Elastic.EaseOut=function(a){var d,e=0.1,b=0.25;if(a==0)return 0;if(a==1)return 1;b||(b=0.3);!e||e<1?(e=1,d=b/4):d=b/(2*Math.PI)*Math.asin(1/e);return e*Math.pow(2,-10*a)*Math.sin((a-d)*2*Math.PI/b)+1};
TWEEN.Easing.Elastic.EaseInOut=function(a){var d,e=0.1,b=0.25;if(a==0)return 0;if(a==1)return 1;b||(b=0.3);!e||e<1?(e=1,d=b/4):d=b/(2*Math.PI)*Math.asin(1/e);return(a*=2)<1?-0.5*e*Math.pow(2,10*(a-=1))*Math.sin((a-d)*2*Math.PI/b):e*Math.pow(2,-10*(a-=1))*Math.sin((a-d)*2*Math.PI/b)*0.5+1};TWEEN.Easing.Back.EaseIn=function(a){return a*a*(2.70158*a-1.70158)};TWEEN.Easing.Back.EaseOut=function(a){return(a-=1)*a*(2.70158*a+1.70158)+1};
TWEEN.Easing.Back.EaseInOut=function(a){return(a*=2)<1?0.5*a*a*(3.5949095*a-2.5949095):0.5*((a-=2)*a*(3.5949095*a+2.5949095)+2)};TWEEN.Easing.Bounce.EaseIn=function(a){return 1-TWEEN.Easing.Bounce.EaseOut(1-a)};TWEEN.Easing.Bounce.EaseOut=function(a){return(a/=1)<1/2.75?7.5625*a*a:a<2/2.75?7.5625*(a-=1.5/2.75)*a+0.75:a<2.5/2.75?7.5625*(a-=2.25/2.75)*a+0.9375:7.5625*(a-=2.625/2.75)*a+0.984375};
TWEEN.Easing.Bounce.EaseInOut=function(a){return a<0.5?TWEEN.Easing.Bounce.EaseIn(a*2)*0.5:TWEEN.Easing.Bounce.EaseOut(a*2-1)*0.5+0.5};TWEEN.Easing.Step.EaseIn=function(){return 0};
Param={exchange:function(a,d,e){e?(e=a,a=d):e=d;a.startX=e.startX;a.startY=e.startY;a.endX=e.endX;a.endY=e.endY;a.left=e.left;a.right=e.right;a.top=e.top;a.bottom=e.bottom;a.width=e.width;a.height=e.height;a.alpha=e.alpha;a.scaleX=e.scaleX;a.scaleY=e.scaleY;a.rotate=e.rotate;a.rotateCenterX=e.rotateCenterX;a.rotateCenterY=e.rotateCenterY;a.customPivot=e.customPivot},tweenParam:function(a,d,e,b){a.startX=d.startX+b*(e.startX-d.startX);a.startY=d.startY+b*(e.startY-d.startY);a.endX=d.endX+b*(e.endX-
d.endX);a.endY=d.endY+b*(e.endY-d.endY);a.width=d.width+b*(e.width-d.width);a.height=d.height+b*(e.height-d.height);a.alpha=d.alpha+b*(e.alpha-d.alpha);a.scaleX=d.scaleX+b*(e.scaleX-d.scaleX);a.scaleY=d.scaleY+b*(e.scaleY-d.scaleY);a.rotate=d.rotate+b*(e.rotate-d.rotate);a.rotateCenterX=d.rotateCenterX+b*(e.rotateCenterX-d.rotateCenterX);a.rotateCenterY=d.rotateCenterY+b*(e.rotateCenterY-d.rotateCenterY);a.customPivot=true;if(d.fillInfo&&d.fillInfo&&(d.fillInfo.fillStyle==1||d.fillInfo.fillStyle==
2))a.fillInfo.fillStartPos.x=d.fillInfo.fillStartPos.x+b*(e.fillInfo.fillStartPos.x-d.fillInfo.fillStartPos.x),a.fillInfo.fillStartPos.y=d.fillInfo.fillStartPos.y+b*(e.fillInfo.fillStartPos.y-d.fillInfo.fillStartPos.y),a.fillInfo.fillEndPos.x=d.fillInfo.fillEndPos.x+b*(e.fillInfo.fillEndPos.x-d.fillInfo.fillEndPos.x),a.fillInfo.fillEndPos.y=d.fillInfo.fillEndPos.y+b*(e.fillInfo.fillEndPos.y-d.fillInfo.fillEndPos.y);a.left=a.startX;a.top=a.startY;a.right=a.startX+a.width;a.bottom=a.startY+a.height}};
Hanimation={PATHMODE_DEFAULT:0};
(function(){Mugeda.initCss3Player=function(){document.addEventListener("mousedown",MugedaCss3.handleCapture,true);document.addEventListener("mouseup",MugedaCss3.handleCapture,true);document.addEventListener("mouseover",MugedaCss3.handleCapture,true);document.addEventListener("mouseout",MugedaCss3.handleCapture,true);document.addEventListener("mousemove",MugedaCss3.handleCapture,true);Mugeda.loadJs=function(b,d,e){if(a(b))d&&d();else{var f=document.createElement("script");f.src=b;document.getElementsByTagName("head")[0].appendChild(f);
f.onload=f.onreadystatechange=function(){!(this.readyState&&this.readyState=="loading")&&d&&(d(),d=function(){})};f.onerror=function(){f.parentNode.removeChild(f);e()}}};var a=function(a){var d=document.getElementsByTagName("script"),e=false;for(b=0;b<d.length;b++)if(d[b].src&&d[b].src.indexOf(a)!=-1&&(d[b].readyState=="loaded"||d[b].readyState=="complete")){e=true;break}return e};Mugeda.startAnimation=function(a,b,d,e,f){var g=navigator.userAgent.toLowerCase();Mugeda.isAndroid=g.indexOf("android")>
-1;Mugeda.androidVersion=parseFloat(g.slice(g.indexOf("android")+8));var j=MugedaCss3.initAnimation(Mugeda.data[a],b,d,e,function(){f&&(MugedaCss3.stage[f]=j)});Mugeda.scene=j;Mugeda.customScript&&Mugeda.customScript.length&&eval(Mugeda.customScript)};if(Mugeda.css3PlayerLoaded==void 0)for(var d=document.getElementsByClassName("MugedaStage"),e=d.length,b=0;b<e;b++){var g=d[b],f=g.getAttribute("mugedaName"),j=MugedaCss3.initAnimation(Mugeda.data[f],g.m_attr("hasScript")=="true"?"actions_"+(f.substr(f.indexOf("_")+
1)+".js"):"",g,g.m_attr("relDir")||"",function(){MugedaCss3.stage[f]=j;--e==0&&typeof Mugeda.script=="function"&&Mugeda.script()});Mugeda.scene=j;Mugeda.customScript&&Mugeda.customScript.length&&eval(Mugeda.customScript)}else if(Mugeda.css3PlayerLoaded=2,Mugeda.creationToBeLoad){for(b=0;b<Mugeda.creationToBeLoad.length;b++)Mugeda.creationToBeLoad[b].start();Mugeda.creationToBeLoad=[]}}})();
document&&document.getElementsByTagName&&document.getElementById&&document.body?Mugeda.initCss3Player():document.addEventListener("DOMContentLoaded",Mugeda.initCss3Player);
