MugedaHelper={};function G(a){return document.getElementById(a)}function E(a,c,b){c||(c="load");b||(b=window);b.attachEvent?b.attachEvent("on"+c,a):b.addEventListener(c,a,false)}function json(a){try{return eval("("+a+")")}catch(c){return null}}function _131(a){if(!a||typeof a=="string")return a;var c="",b;for(b in a)c+="&"+b+"="+encodeURIComponent(a[b]);c&&(c=c.substr(1));return c}
function ajax(a){var c=/POST/i.test(a.type),b=a.data||"",d=a.dataType,g=a.url||location.href,i=/\?/.test(g)?"&":"?",h=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Msxml2.XMLHTTP")||new ActiveXObject("Microsoft.XMLHTTP");h.onreadystatechange=function(b){if(h.readyState==4)h.status==200?(b=h.responseText,d=="json"&&(b=json(b)),(c=a.success)&&c(b)):a.error&&a.error(h.status,h)};if(typeof b=="object"){var l=[],f;for(f in b)l.push(encodeURIComponent(f)+"="+encodeURIComponent(b[f]));b=l.join("&")}h.open(c?
"POST":"GET",g+(c?"":(b?i:"")+b+(a.cache?"":(!b&&i=="?"?"?":"&")+"_="+(new Date).getTime())),a.async===false?false:true);c&&h.setRequestHeader("Content-Type","application/x-www--urlencoded");h.send(b);return h}
function isMobile(){return navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/BlackBerry/i)||navigator.userAgent.match(/Windows Phone/i)?true:false}function fo(a){var c=0,b=0;do c+=a.offsetLeft||0,b+=a.offsetTop||0;while(a=a.offsetParent);return{x:c,y:b}}function fe(a){a=a||event;return{x:a.pageX||a.x,y:a.pageY||a.y}}
function fc(a){a&&a.stopPropagation?a.stopPropagation():event.cancelBubble=true}function getClass(a,c){for(var b=RegExp("(^|\\s*)"+a+"(\\s*|$)"),d=c?document.getElementsByTagName(c):document.getElementsByTagName("*")||document.all,g=[],i=0,h=d.length;i<h;i++)b.test(d[i].className)&&g.push(d[i]);return g}JSON.clone=function(a){return JSON.parse(JSON.stringify(a))};
function getElementOffset(a){for(var c=0,b=0;a&&a.tagName!="BODY";)c+=a.offsetTop,b+=a.offsetLeft,a=a.offsetParent;return{top:c,left:b}}
MugedaMraid={mraidReadyStatus:0,mraidState:void 0,getStage:function(){var a=null;for(window.event&&(a=window.event.target||window.event.srcElement);a;){if(a.id.indexOf("_stage")>0)break;a=a.parentNode}return a?a:document.getElementsByClassName("MugedaStage")[0]},setMraidState:function(a){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;var c=_mrmcp.display_mode,b=mraid.getPlacementType();this.mraidState=a.toLowerCase();var d=document.getElementById("mugeda_close_button");switch(this.mraidState){case "default":if(c!=
"expand"&&b!="interstitial"&&d)d.style.display="none";typeof Mugeda!="undefined"&&Mugeda.gotoAndPlay&&Mugeda.gotoAndPlay(1);break;case "expanded":(c=="auto"||c=="expand"||c=="interstitial")&&setTimeout(function(){d.style.display="block"},50);break;case "resized":setTimeout(function(){d.style.display="block"},50)}},openLink:function(a,c){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;_mrmcp.destination_url&&_mrmcp.destination_url.indexOf("%DESTURL%")<0&&(a=_mrmcp.destination_url);var b="ts="+(new Date).getTime();
b+="&_moid="+(_mrmcp.owner_id||"");b+="&_mcid="+(_mrmcp.creative_id||"");b+="&_mw="+(_mrmcp.width||"");b+="&_mh="+(_mrmcp.height||"");b+="&_mtp="+(_mrmcp.type||"");b+="&_mtt="+escape(_mrmcp.title||"");var d=_mrmcp.custom_params;d&&d.indexOf("%CUSTOMPARAM%")<0&&(b+="&"+d);if((d=_mrmcp.redirect_url)&&d.indexOf("%LINK%")<0)var g=a.indexOf("?"),g=g<0?"?":"&",a=d+(d.lastIndexOf("=")==d.length-1?escape(a+g+b):"");var g=a.indexOf("?"),d=g<0?"?":"&",g=g==a.length-1,i=window.location.search;if(i){for(var i=
i.split("?")[1],h=i.split("&"),l=h.length,f=0;f<l;f++){var j=h[f].split("=");if(j.length==2){var n=j[1];j[0].toLowerCase()=="mugeda_click_link"&&(a=unescape(n),g=a.indexOf("?"),d=a<0?"?":"&",g=g==a.length-1)}}a+=(g?"":d)+i;g=false;i.length&&(d="&")}a+=(g?"":d)+b;this.mraidReadyStatus==1?c=="internal"?mraid.open(a):c=="expand"?this.expand(a,0):window.open(a):c=="internal"?window.location=a:c=="expand"?this.expand(a):window.open(a);MugedaTracker.fireEvent({category:"link",action:c,label:a,value:0})},
expand:function(a,c,b){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;if(this.mraidReadyStatus!=1){if(a&&a.length){var d=document.URL.match(/client.*preview.*id/),g=b=null;try{b=(d?window:window.parent).document,g=b.getElementById("mugeda_expanded")||b.createElement("div")}catch(i){window.open(a);return}a.match(/^(\/|http:|https:)/i)||(a=(_mrmcp.creative_path||"")+a);g.id="mugeda_expanded";g.style.display="block";g.style.position="fixed";g.style.width=(b.defaultView.innerWidth||b.documentElement.clientWidth)+
"px";g.style.height=(b.defaultView.innerHeight||b.defaultView.innerHeight)+"px";g.style.left="0px";g.style.margin="0";g.style.padding="0";g.style.border="none";g.style.top="0px";g.style.background="#000";g.innerHTML="<iframe id='mugeda_expand_iframe' src='"+a+"' style='border:none;width:100%;height:100%;margin:0px;padding:0px;'></iframe>";b.body.appendChild(g);MugedaBehavior.processCloseButton("expand",b)}}else{var b=b||{},g=mraid.getMaxSize(),d=parseInt(b.width)||g.width,g=parseInt(b.height)||g.height,
a=a||b.url,h=!a||a.length==0;c==1?(a=parseInt(b.left)||0,b=parseInt(b.top)||0,MugedaBehavior.processCloseButton("resize"),mraid.setResizeProperties({width:d,height:g,offsetX:a,offsetY:b,allowOffscreen:false}),mraid.resize()):(mraid.setExpandProperties({width:d,height:g,isModal:true,useCustomClose:_mrmcp.display_mode?true:false}),h?(mraid.expand(),MugedaBehavior.processCloseButton()):mraid.expand(a))}},sendEmail:function(a){window.open("mailto:"+a.email_addr+"?subject="+a.email_title+"&body="+a.email_body,
"_self")},savePicture:function(a){this.mraidReadyStatus==1&&mraid.supports("storePicture")&&mraid.storePicture(a.url)},addCalendarEvent:function(a){this.mraidReadyStatus==1&&mraid.supports("calendar")&&mraid.createCalendarEvent({summary:a.calendar_summary,description:a.calendar_desc,location:a.calendar_location,start:a.calendar_start_time,end:a.calendar_end_time})},createHTML5VideoTag:function(){var a=G("mugedaVideoHolder");if(a)return a;a=document.createElement("div");a.id="mugedaVideoHolder";a.style.margin=
0;a.style.padding=0;a.style.backgroundColor="rgba(0,0,0,0.8)";a.style.position="fixed";a.style.top=0;a.style.left=0;a.style.width=0;a.style.height=0;_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;var c=(_mrmcp.creative_path||"")+"close_button.png",c='<video id="mugeda_video" onclick="this.play();" style="width:100%;height:100%;"></video>'+('<div id="mugeda_video_close" align="middle" style="position: absolute;color:white;width: 36px;height: 36px;right: 0px;top: '+(navigator.userAgent.match(/iPhone/i)||
navigator.userAgent.match(/iPad/i)?-18:0)+"px;cursor:pointer;background-image: url("+c+');"></div>');a.innerHTML=c;a.style.display="none";document.body.appendChild(a);G("mugeda_video").onclick=function(){this.paused?this.play():this.pause()};return a},loadUrl:function(a){var c=a.id||(new Date).getTime(),b=a.url||"",d=a.left||0,g=a.top||0,i=isNaN(a.width)?window.aniData?window.aniData.width:320:Math.max(0,a.width),h=isNaN(a.height)?window.aniData?window.aniData.height:240:Math.max(0,a.height),l=a.before||
null,f=a.style,j=a.scroll,n=a.parent,w=a.onload,v=a.onclose,x=a.position,q=a.close_position;if(!l&&!n){var u=typeof Mugeda!="undefined"&&Mugeda.getCanvas?Mugeda.getCanvas():this.getStage();typeof Mugeda!="undefined"&&u&&(u=getElementOffset(u),d+=u.left,g+=u.top)}var e=G(c);e||(e=document.createElement("div"),n?n.appendChild(e):l?l.parentNode.insertBefore(e,l):document.body.appendChild(e));e.id=c;e.style.margin=0;e.style.padding=0;e.style.backgroundColor="transparent";e.style.position=x?x:"fixed";
e.style.top=0;e.style.left=0;e.style.width=0;e.style.height=0;switch(q){case "leftTop":q="left:4px;top:4px;";break;case "leftbottom":q="left:4px;bottom:4px;";break;case "rightbottom":q="right:4px;bottom:4px;";break;default:q="right: 4px;top: 4px;"}e.innerHTML="<iframe "+(j?"":"scrolling=no ")+'id="'+c+'_iframe" style="border:none; width:100%;height:100%; '+(j?"":"overflow:hidden;")+' " ></iframe>'+('<div id="'+c+'_iframe_close" align="middle" style="position: absolute;color:white;width: 24px;height: 24px; '+
q+'cursor:pointer;background: rgba(0,0,0,0.5);border: 3px solid white;border-radius: 15px;font-family:arial;font-size: 16px;line-height:24px;">&#10006;</div>');e.style.display="none";e.style.top=g+"px";e.style.left=d+"px";e.style.width=i+"px";e.style.height=h+"px";e.style.display="block";e.style.cssText+=f;G(c+"_iframe_close").style.display=a.close_button?"block":"none";setTimeout(function(){if(a.close_button)G(c+"_iframe_close").onclick=function(){e.style.display="none";G(c+"_iframe").src="about:blank";
v&&v(e)}},100);setTimeout(function(){var a=G(c+"_iframe");a.src=b;if(w)try{a.onload=function(){w(a);a.onload=null}}catch(e){}},100);return e},playAudio:function(a,c){var b=false;if(!a||!a.audio_url||!a.audio_url.length)return false;var d=typeof Mugeda!="undefined"&&Mugeda.getAudioCache?Mugeda.getAudioCache(a.audio_url,a.audioId):MugedaBehavior.localCache[a.audio_url];if(d){if(d.loop=parseInt(a.audio_loop)==1?true:false,d.play)if(d.webAudio)b=d.play(a.event=="click"||c?true:false);else if(a.event==
"click"){try{d.pause(),d.currentTime=0}catch(g){}setTimeout(function(){d.play()},5)}else(d._DF!=1||c)&&setTimeout(function(){d.play();d._DF=1;b=true},10)}else{var d=new Audio,i=document.createElement("source"),h=a.audio_url.lastIndexOf("."),h=a.audio_url.substring(h+1),l=true;switch(h){case "ogg":i.type="audio/ogg";break;case "mp3":i.type="audio/mpeg";break;default:l=false,console.log("Audio extension ("+h+") not supported.")}if(l){i.src=a.audio_url;d.appendChild(i);d.autoplay=false;d.preload="auto";
d.load();var f=document.getElementById("mugeda_resource_loading");if(!f)f=document.createElement("img"),f.id="mugeda_resource_loading",f.style.position="fixed",f.style.right="2px",f.style.top="2px",f.style.display="block",f.src="loading.gif",document.body.appendChild(f);f.style.display="block";b=true;d.addEventListener("canplay",function(){f.style.display="none";d.play()},false);MugedaBehavior.localCache[a.audio_url]=d}}return b},playHTML5Video:function(a){var c=a.left||0,b=a.top||0,d=isNaN(a.width)?
window.aniData?window.aniData.width:320:Math.max(0,a.width),g=isNaN(a.height)?window.aniData?window.aniData.height:240:Math.max(0,a.height),i=typeof Mugeda!="undefined"&&Mugeda.getCanvas?Mugeda.getCanvas():this.getStage();typeof Mugeda!="undefined"&&i&&(i=getElementOffset(i),c+=i.left,b+=i.top);i=this.createHTML5VideoTag();(i=G("mugedaVideoHolder"))||(i=document.createElement("div"));i.style.top=b+"px";i.style.left=c+"px";i.style.width=d+"px";i.style.height=g+"px";i.style.display="block";var h=G("mugeda_video");
G("mugeda_video_close").style.display=a.close_button?"block":"none";a.video_controls?h.setAttribute("controls","controls"):h.removeAttribute("controls");h.src=a.url;h.load();setTimeout(function(){h.play();setTimeout(function(){if(a.close_button)G("mugeda_video_close").onclick=function(){var a=G("mugeda_video");if(a)a.src="",a.load();G("mugedaVideoHolder").style.display="none"}},1E3)},10)},playVideo:function(a){this.mraidReadyStatus!=1?this.playHTML5Video({url:a.video_url,left:parseInt(a.video_left),
top:parseInt(a.video_top),width:parseInt(a.video_width),height:parseInt(a.video_height),close_button:parseInt(a.video_close)==1,video_controls:parseInt(a.video_controls)==1,auto:parseInt(a.video_autoplay)==1}):mraid.playVideo(a.video_url)},sendShortMessage:function(a){window.open("sms:"+a.phone_number+"?body="+a.sms_body,"_self")},makePhoneCall:function(a){window.open("tel:"+a.phone_number,"_self")}};
MugedaBehavior={localCache:{},pause:function(){typeof Mugeda!="undefined"&&Mugeda.pause&&Mugeda.pause()},resume:function(a){typeof Mugeda!="undefined"&&Mugeda.resume&&Mugeda.resume(a)},next:function(){typeof Mugeda!="undefined"&&Mugeda.next&&Mugeda.next()},previous:function(){typeof Mugeda!="undefined"&&Mugeda.previous&&Mugeda.previous()},gotoAndPlay:function(a){typeof Mugeda!="undefined"&&Mugeda.gotoAndPlay&&Mugeda.gotoAndPlay(a)},gotoAndStop:function(a){gotoAndPause(a)},gotoAndPause:function(a){typeof Mugeda!=
"undefined"&&Mugeda.gotoAndPause&&Mugeda.gotoAndPause(a)},callback:function(a,c){if(window&&c.name&&c.name.length&&window[c.name])window[c.name](a,c.key,c.value)},map:function(a){function c(a,b,c){a="https://maps.google.com/maps?q="+(a+""+(b.length?"+near+"+b:""))+"&z=12";b=parseFloat((""+(/CPU.*OS ([0-9_]{1,5})|(CPU like).*AppleWebKit.*Mobile/i.exec(navigator.userAgent)||[0,""])[1]).replace("undefined","3_2").replace("_",".").replace("_",""))||false;if(c==1){if(c=document.getElementById("aMugedaGeoLocation"))c.href=
a,a=document.createEvent("HTMLEvents"),a.initEvent("click",true,true),c.dispatchEvent(a)}else b&&b<6?window.location.href=a:window.open(a,"_blank")}var b=a.map_key.replace(/(\n|\r)/g,"+"),d=a.map_address.replace(/(\n|\r)/g,"+");if(!(navigator.userAgent.toLowerCase().indexOf("android")>-1)&&d.length==0&&navigator.geolocation){a=document.getElementById("aMugedaGeoLocation");if(!a)a=document.createElement("a"),a.id="aMugedaGeoLocation",a.style.display="none",a.href="",a.target="_blank",document.body.appendChild(a);
navigator.geolocation.getCurrentPosition(function(a){d=a.coords.latitude+","+a.coords.longitude;c(b,d,1)})}else c(b,d)},popupForm:function(a){function c(a){var b,c,e,d=document.cookie.split(";");for(b=0;b<d.length;b++)if(c=d[b].substr(0,d[b].indexOf("=")),e=d[b].substr(d[b].indexOf("=")+1),c=c.replace(/^\s+|\s+$/g,""),c==a.toLowerCase())return unescape(e);return""}function b(a,b){var c=new Date;c.setDate(c.getDate()+3);c=escape(b)+"; expires="+c.toUTCString();document.cookie=a.toLowerCase()+"="+c}
function d(a){var b=document.querySelector(".MugedaStage")?null:G("viewbox")||G("frame");if(b)b.style.display=a?"":"none";return b?true:false}function g(a){document.body.removeChild(a);if(d(1)&&(document.body.style.overflowY="hidden",isMobile()))document.body.style.height="100%"}if(a&&!(a.openTarget=="callback"&&!a.callback||a.openTarget!="callback"&&!a.url)){var i=document.documentElement.clientWidth,h=document.documentElement.clientHeight,l=[];if(!a.html){var f="";a.title&&(f+='<div align="center"><h2>'+
a.title+"</h2></div>");var j=a.items||[];window.popupFormFields=j;var n=navigator.userAgent.toLowerCase(),w=n.indexOf("android")>-1,v=parseFloat(n.slice(n.indexOf("android")+8)),x="",q=0;w&&v<3&&(x="-webkit-transform: scale(2,2);-webkit-transform-origin:center center;");for(var u=Math.max(0,6-j.length),n=0;n<j.length;n++){var e=j[n],p=(e.value||"").trim();if(p){for(var p=p.split("\n"),m=[],o=0;o<p.length;o++){var y=p[o].split("("),r=y[0],y=(y[1]||"").replace(/\)$/,"")||r,t=["FORMID",y,n,o].join("_");
m[o]={id:t,text:r,value:y}}p=m}t='id="popupFormField_'+n+'"';switch(e.type){case "radio":f+="<div "+t+' class="popupFormRadioList">';e.description&&(f+="<h3>"+e.description+(e.required?"*":"")+":</h3>");f+='<div class="mformradio">';for(o=0;o<p.length;o++)m=p[o],r=c(m.id),f+='<label><input type="radio" name="'+e.id+'" value="'+m.value+'" id="'+m.id+'" '+(r=="true"?"checked=checked":"")+" ><span "+(o==p.length-1?"":" style='border-right:1px solid #ccc'")+">"+m.text+"</span></label>",l[m.id]=m.id;f+=
"</div></div>";break;case "checkbox":f+="<div "+t+' class="popupFormCheckbox">';e.description&&(f+="<h3>"+e.description+(e.required?"*":"")+":</h3>");f+='<div class="mformcheck">';f+=e.rangeType==="vertical"?"<table>":"";for(o=0;o<p.length;o++)m=p[o],r=c(m.id),f+=e.rangeType==="vertical"?'<tr><td><input type="checkbox" value="'+m.value+'" id="'+m.id+'" '+(r=="true"?"checked=true":"")+' ></td><td><label for="'+m.id+'" >'+m.text+"</label></td></tr>":'<input type="checkbox" value="'+m.value+'" id="'+
m.id+'" '+(r=="true"?"checked=true":"")+' ><label for="'+m.id+'" >'+m.text+"</label>",l[m.id]=m.id;w&&v<3&&e.rangeType!="vertical"&&(q=6);f+=e.rangeType==="vertical"?"</table>":"";f+="</div></div>";break;case "select":f+="<div "+t+' class="popupFormSelectList">';e.description&&(f+='<label class="inputlabel">'+e.description+(e.required?"*":"")+":</label>");f+='<select id="_map_'+e.description+'">';e.required&&(f+='<option value=""></option>');r=c(e.description);for(o=0;o<p.length;o++)m=p[o],f+='<option value="'+
m.value+'" '+(r==m.value?"selected=selected":"")+">"+m.text+"</option>";f+="</select>";f+="</div>";l[e.description]="_map_"+e.description;break;case "phone":f+="<div "+t+' class="popupFormInputBox">';f+='<label class="inputlabel">'+e.description+(e.required?"*":"")+':</label><input id="_mcp_'+escape(e.description)+'" type="telephone" value="'+(e.value.length?e.value:c(e.description))+'" >';f+="</div>";l[e.description]="_mcp_"+escape(e.description);break;case "email":f+="<div "+t+' class="popupFormInputBox">';
f+='<label class="inputlabel">'+e.description+(e.required?"*":"")+':</label><input id="_mcp_'+escape(e.description)+'" type="email" value="'+(e.value.length?e.value:c(e.description))+'" >';f+="</div>";l[e.description]="_mcp_"+escape(e.description);break;case "textarea":f+="<div "+t+' class="popupFormInputBox">';f+='<label class="inputlabel">'+e.description+(e.required?"*":"")+':</label><textarea id="_mcp_'+escape(e.description)+'" rows="4" style="resize:none; height:48px;">'+(e.value.length?e.value:
c(e.description))+"</textarea>";f+="</div>";l[e.description]="_mcp_"+escape(e.description);break;default:f+="<div "+t+' class="popupFormInputBox">',f+='<label class="inputlabel">'+e.description+(e.required?"*":"")+':</label><input id="_mcp_'+escape(e.description)+'" type="text" value="'+(e.value.length?e.value:c(e.description))+'" >',f+="</div>",l[e.description]="_mcp_"+escape(e.description)}}f+='<div class="popupFormButtons">';f+='<input id="actionButton" type="submit" value="'+a.submitName+'" class="popupFormSubmit">';
f+='<input type="button" value="'+a.cancelName+'" class="popupFormCancel" id="popupFormCancel">';f+="</div>";a.html=f}var k=this.popupFormDiv;if(!k){if(!k){var z=a.openTarget=="backend"?"popupFormIframe":"_"+a.openTarget,k=document.createElement("div");k.style.display="none";k.className="popupForm";k.innerHTML='<form method="'+a.method+'" target="'+z+'" autocomplete="on"></form><iframe name="popupFormIframe" id="popupFormIframe" style="display:none"></iframe><style>.popupForm{width:288px;background:'+
a.background+";font-size:"+a.fontSize+'px;font-family:Tahoma,"\u5fae\u8f6f\u96c5\u9ed1",Arial, SimHei;}.popupForm, .popupForm form{border-radius:4px;}.popupForm *{margin:0;}.popupForm .inputlabel{margin:4px 8px;width:96px;height:28px;font-size:'+a.fontSize+"px;line-height:28px;display:inline-block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;vertical-align:middle;}.popupForm span{color:#333;}.popupForm label{color:"+a.color+";}.popupForm h2{border-radius:2px 2px 0 0;padding:8px;font-weight:bold;font-size:"+
(2+parseInt(a.fontSize))+"px;background-color:rgba(255,255,255,0.5);color:"+a.color+";}.popupForm h3{text-align:left;font-size:"+a.fontSize+"px; font-weight: normal;color:"+a.color+";}.popupFormInputBox{padding:"+u+"px 0;text-align:left;}.popupFormInputBox input, .popupFormInputBox textarea, .popupFormSelectList select{border-radius:4px;margin:4px 8px;width:148px;height:28px;border:1px solid #bbb;font-size:"+a.fontSize+"px;padding:0;padding-left:8px;vertical-align:middle;}.popupFormSelectList{padding:0px;}.popupFormButtons{padding:8px;text-align:center;}.popupFormButtons input{width:96px; height:28px;border-radius:4px;border-width:1px;font-size:"+
a.fontSize+"px;}.popupFormSubmit{margin-right:20px;background-color:#EEEEEE;border-color:#DDDDDD;}.popupFormCancel{background-color:#EEEEEE;border-color:#DDDDDD;}.popupFormRadioList{padding:8px;height:64px;}.popupFormRadioList input{margin:0 5px 0 8px;}.popupFormCheckbox{padding:8px 8px 0 8px;}.mformradio{margin:8px 0;background-color:#EFEFEF;border-radius:8px;border:1px solid #AAAAAA;overflow:hidden;float:left;}.mformradio label{float:left; min-width:64px;}.mformradio label span{text-align:center;padding:6px 8px;display:block;}.mformradio label input{position:absolute;top:-99999px;}.mformradio input:checked + span{background-color:#0080ff;color:#F7F7F7;}.mformcheck{margin:8px 0;}.mformcheck input{"+
x+"width:24px;height:24px;background-color:#EFEFEF;vertical-align:middle;margin:3px 2px;}.mformcheck input:checked{background-color:#0080ff;}.mformcheck label{vertical-align:"+q+"px;font-size:"+a.fontSize+"px;padding-top:0;padding-left:4px;padding-right:8px;}</style>";document.body.appendChild(k);this.popupFormDiv=k;k.form=k.childNodes[0];k.form.onclick=function(a){a.cancelBubble=false};self=this;k.form.onsubmit=function(){function c(){for(var b=[],d=window.popupFormFields,e=0;e<d.length;e++){var f=
d[e],i=G("popupFormField_"+e),h="",j=i.querySelectorAll("select");j.length==0&&(j=i.querySelectorAll("textarea"),j.length==0&&(j=i.querySelectorAll("input")));if(j.length==1)h=j[0].value||"";else if(j.length>1){for(var h=[],l=0;l<j.length;l++)if(i=j[l],i.checked&&(h.push(i.value),i.type=="radio"))break;h=h.join(",")}if(f.required&&!h){alert((f.description||"item")+" required");j[0].focus();return}if(h)switch(f.type){case "phone":if(!/^\d+$/.test(h)){alert("Phone number required");j[0].focus();return}break;
case "email":if(!/^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/.test(h)){alert("Email required");j[0].focus();return}}b.push(encodeURIComponent(f.id)+"="+encodeURIComponent(h||""))}if("popupFormIframe"==z)G("actionButton").value=a.pendingName;b=b.join("&");d=a.url+"?"+b;a.loadFinished=function(){g(k);self.popupFormDiv=null};if(a.openTarget=="callback")a.callback&&window[a.callback]?(d={callback:function(){alert(a.msg)},cancel:false},window[a.callback](b,d),MugedaTracker.fireEvent({category:"interaction",
action:"form",label:"",value:a.id?parseInt(a.id,36):0}),d.cancel!==true&&d.callback()):console.log("No callback function found. Skipping..."),a.loadFinished();else try{window.open(d,z),G("popupFormIframe").onload=function(){a.loadFinished();MugedaTracker.fireEvent({category:"interaction",action:"form",label:"",value:a.id?parseInt(a.id,36):0});alert(a.msg)}}catch(m){a.loadFinished(),alert("Form submission failed. Please try again. ")}}G("popupFormIframe").onload=null;for(e in l){var d=document.getElementById(l[e]);
d&&(d.type=="checkbox"||d.type=="radio"?b(e,d.checked):b(e,d.value))}v<3?c():setTimeout(c,200);return false}}k.style.display="";k.form.innerHTML=a.html;if(a.id)k.form.id=a.id;if(a.background)k.form.style.background=a.background;k.style.display="";k.style.visibility="hidden";setTimeout(function(){k.style.visibility="visible"},100);setTimeout(function(){G("popupFormCancel").onclick=function(){g(k);self.popupFormDiv=null}},500);f=document.querySelectorAll(".popupFormInput");for(n=0;n<f.length;n++)j=
f[n],j.onfocus=onInputFocus,j.onblur=onInputBlur;h=a.target?a.target.getBoundingClientRect():{left:0,top:0,width:i,height:h};document.body.style.overflowY="auto";if(d()){if(k.style.marginLeft=Math.max(2,h.left+document.documentElement.scrollLeft+(h.width-k.offsetWidth)/2)+"px",k.style.marginTop=Math.max(2,h.top+document.documentElement.scrollTop+(h.height-k.offsetHeight)/2)+"px",k.style.marginBottom="32px",k.offsetHeight+32>document.documentElement.scrollHeight&&(k.style.marginTop=parseInt(window.getComputedStyle?
getComputedStyle(k).marginTop:k.currentStyle.marginTop)+32+"px",isMobile()))document.body.style.height=k.offsetHeight+64+"px"}else k.style.position="absolute",k.style.background="rgba(0,0,0,0.5)",k.style.left=0,k.style.top=0,i=Math.max(2,h.top+(h.height-k.offsetHeight)/2)+"px",h=Math.max(2,h.left+(h.width-k.offsetWidth)/2)+"px",k.style.paddingLeft=h,k.style.paddingTop=i,k.style.paddingRight=h,k.style.paddingBottom=i}}},processAction:function(a,c,b){var d=true;if(a.type=="pause")this.pause(a.param);
else if(a.type=="play")this.resume(1);else if(a.type=="next")this.next();else if(a.type=="previous")this.previous();else if(a.type=="callback")this.callback(a.object,a.param);else if(a.type=="map")this.map(a.param);else if(a.type=="gotoAndPlay")this.gotoAndPlay(a.param&&a.param.frame_number>=0?a.param.frame_number:parseInt(a.param));else if(a.type=="gotoAndPause"||a.type=="gotoAndStop")this.gotoAndPause(a.param&&a.param.frame_number>=0?a.param.frame_number:parseInt(a.param));else if(a.type=="call")MugedaMraid.makePhoneCall(a.param);
else if(a.type=="sms")MugedaMraid.sendShortMessage(a.param);else if(a.type=="email")MugedaMraid.sendEmail(a.param);else if(a.type=="video")MugedaMraid.playVideo(a.param);else if(a.type=="audio"){a.param.event=c;var d=Mugeda.getMugedaObject().scene.currentId,g=false;a.unit&&a.unit.frameStart==d&&(g=true);d=MugedaMraid.playAudio(a.param,g)}else a.type=="picture"?MugedaMraid.savePicture(a.param):a.type=="calendar"?MugedaMraid.addCalendarEvent(a.param):a.type=="expand"?MugedaMraid.expand(a.param.url,
0,a.param):a.type=="resize"&&MugedaMraid.expand("",1,a.param);g="actoin_type="+a.type+"&refid="+(new Date).getTime();for(item in a.param)g+="&"+item+"="+a.param[item];c=="click"&&window.event&&window.event.stopPropagation&&window.event.stopPropagation();d&&b&&a.param.event_name&&MugedaTracker.fireEvent({category:"interaction",action:a.param.event_name,label:g,value:0})},processCloseButton:function(a,c){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;var b=c,d=null;if(!b)try{window!=window.parent?(b=window.parent.document,
d=window.frameElement):b=document}catch(g){b=document}if(b){var i=null;try{i=window.parent.document,i.getElementById("mugeda_expanded")||i.createElement("div")}catch(h){return}var l=a||_mrmcp.display_mode,f=MugedaMraid.mraidReadyStatus==1?mraid.getPlacementType():"default",j=b.getElementById("mugeda_close_button");if(!j)j=b.createElement("img"),j.id="mugeda_close_button",j.style.cursor="pointer",j.style.zIndex=99999,j.style.display="block",j.style.position="fixed",j.style.right="0",j.style.top="0",
j.addEventListener("click",function(){if(MugedaMraid.mraidReadyStatus!=1){b.body.removeChild(j);l=="interstitial"&&d&&d.parentNode.removeChild(d);var a=b.getElementById("mugeda_expanded");a&&b.body.removeChild(a)}}),b.body.appendChild(j);if(f=="interstitial"||l=="auto"||l=="resize"||l=="expand"||l=="interstitial")j.src=(_mrmcp.creative_path||"")+"close_button.png",j.onerror=function(){j.style.display="none"},j.onload=function(){j.style.display=f=="interstitial"||l!="auto"?"block":"none"}}}};
MugedaTracker={fireEvent:function(a){if(!window.location||!window.location.host){var a=(_mrmcp.track_bot||"http://cdn.mugeda.com/media/pages/track/track_20131030.html")+"?"+(_mrmma_var1||"var1=none")+"&"+(_mrmma_var2||"var2=none")+"&category="+a.category+"&action="+a.action+"&label="+encodeURIComponent(a.label)+"&value="+a.value+"&noninteraction="+a.noninteraction,c=document.createElement("iframe");c.id=_mrmcp.creative_id;c.src=a;c.style.display="none";c.style.width="1px";c.style.height="1px";document.body.appendChild(c)}else if(this.fireGAEvent(a.category,
a.action,a.label,a.value,a.noninteraction),window.mugedaGetCustomTracker&&(c=window.mugedaGetCustomTracker())){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;var b=_mrmcp.custom_params,d=_mrmma_tags;b&&b.indexOf("%CUSTOMPARAM%")<0&&(d+="&"+b);c(d,a.category,a.action,a.label,a.value)}},fireGAEvent:function(a,c,b,d,g){typeof _gaq!="undefined"&&(_gaq.push(["_trackEvent",a,c,b,d,g]),typeof _ga_mugeda_use_custom!="undefined"&&_gaq.push(["custom._trackEvent",a,c,b,d,g]))}};
function mraidReady(){parseFloat(mraid.getVersion())-0.999>0?(MugedaMraid.mraidReadyStatus=1,_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp,_mrmcp.display_mode&&(mraid.useCustomClose(true),MugedaBehavior.processCloseButton()),mraid.addEventListener("error",function(){}),mraid.addEventListener("stateChange",function(){var a=mraid.getState();MugedaMraid.setMraidState(a)}),mraid.addEventListener("sizeChange",function(){})):console.log("mraidReady is called, but with no correct version (>= 1.0) supported.")}
var mraidReadyTimeout,mraidTimeOut=100,mraidCounter=0;function readyListener(){typeof mraid==="undefined"?(mraidCounter++,mraidCounter<mraidTimeOut&&(mraidReadyTimeout=setTimeout(readyListener,100))):mraid.getState()==="loading"?mraid.addEventListener("ready",mraidReady):mraidReady()}readyListener();
try{var htmlDoc=document.getElementsByTagName("head").item(0),js=document.createElement("script"),s="mraid.js";js.setAttribute("type","text/javascript");js.setAttribute("src",s);htmlDoc.appendChild(js);js.onload=function(){};js.onerror=function(){}}catch(e$$17){alert(e$$17.toString())};
